package com.google.appinventor.components.runtime;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.MenuItem.OnMenuItemClickListener;
import android.widget.Toast;
import com.google.appinventor.components.runtime.util.AppInvHTTPD;
import com.google.appinventor.components.runtime.util.RetValManager;
import dalvik.system.DexClassLoader;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import java.util.Set;

public class ReplForm
  extends Form
{
  private static final String REPL_ASSET_DIR = "/sdcard/AppInventor/assets/";
  private static final String REPL_COMP_DIR = "/sdcard/AppInventor/assets/external_comps/";
  public static ReplForm topform;
  private boolean IsUSBRepl = false;
  private boolean assetsLoaded = false;
  private AppInvHTTPD httpdServer = null;
  private boolean isDirect = false;
  private List<String> loadedExternalDexs;
  private Object replResult = null;
  private String replResultFormName = null;
  
  public ReplForm()
  {
    topform = this;
  }
  
  private void checkAssetDir()
  {
    File localFile = new File("/sdcard/AppInventor/assets/");
    if (!localFile.exists()) {
      localFile.mkdirs();
    }
  }
  
  private void checkComponentDir()
  {
    File localFile = new File("/sdcard/AppInventor/assets/external_comps/");
    if (!localFile.exists()) {
      localFile.mkdirs();
    }
  }
  
  private String genReportId()
  {
    String[] arrayOfString = new String['ࠀ'];
    arrayOfString[0] = "A";
    arrayOfString[1] = "ABE";
    arrayOfString[2] = "ACE";
    arrayOfString[3] = "ACT";
    arrayOfString[4] = "AD";
    arrayOfString[5] = "ADA";
    arrayOfString[6] = "ADD";
    arrayOfString[7] = "AGO";
    arrayOfString[8] = "AID";
    arrayOfString[9] = "AIM";
    arrayOfString[10] = "AIR";
    arrayOfString[11] = "ALL";
    arrayOfString[12] = "ALP";
    arrayOfString[13] = "AM";
    arrayOfString[14] = "AMY";
    arrayOfString[15] = "AN";
    arrayOfString[16] = "ANA";
    arrayOfString[17] = "AND";
    arrayOfString[18] = "ANN";
    arrayOfString[19] = "ANT";
    arrayOfString[20] = "ANY";
    arrayOfString[21] = "APE";
    arrayOfString[22] = "APS";
    arrayOfString[23] = "APT";
    arrayOfString[24] = "ARC";
    arrayOfString[25] = "ARE";
    arrayOfString[26] = "ARK";
    arrayOfString[27] = "ARM";
    arrayOfString[28] = "ART";
    arrayOfString[29] = "AS";
    arrayOfString[30] = "ASH";
    arrayOfString[31] = "ASK";
    arrayOfString[32] = "AT";
    arrayOfString[33] = "ATE";
    arrayOfString[34] = "AUG";
    arrayOfString[35] = "AUK";
    arrayOfString[36] = "AVE";
    arrayOfString[37] = "AWE";
    arrayOfString[38] = "AWK";
    arrayOfString[39] = "AWL";
    arrayOfString[40] = "AWN";
    arrayOfString[41] = "AX";
    arrayOfString[42] = "AYE";
    arrayOfString[43] = "BAD";
    arrayOfString[44] = "BAG";
    arrayOfString[45] = "BAH";
    arrayOfString[46] = "BAM";
    arrayOfString[47] = "BAN";
    arrayOfString[48] = "BAR";
    arrayOfString[49] = "BAT";
    arrayOfString[50] = "BAY";
    arrayOfString[51] = "BE";
    arrayOfString[52] = "BED";
    arrayOfString[53] = "BEE";
    arrayOfString[54] = "BEG";
    arrayOfString[55] = "BEN";
    arrayOfString[56] = "BET";
    arrayOfString[57] = "BEY";
    arrayOfString[58] = "BIB";
    arrayOfString[59] = "BID";
    arrayOfString[60] = "BIG";
    arrayOfString[61] = "BIN";
    arrayOfString[62] = "BIT";
    arrayOfString[63] = "BOB";
    arrayOfString[64] = "BOG";
    arrayOfString[65] = "BON";
    arrayOfString[66] = "BOO";
    arrayOfString[67] = "BOP";
    arrayOfString[68] = "BOW";
    arrayOfString[69] = "BOY";
    arrayOfString[70] = "BUB";
    arrayOfString[71] = "BUD";
    arrayOfString[72] = "BUG";
    arrayOfString[73] = "BUM";
    arrayOfString[74] = "BUN";
    arrayOfString[75] = "BUS";
    arrayOfString[76] = "BUT";
    arrayOfString[77] = "BUY";
    arrayOfString[78] = "BY";
    arrayOfString[79] = "BYE";
    arrayOfString[80] = "CAB";
    arrayOfString[81] = "CAL";
    arrayOfString[82] = "CAM";
    arrayOfString[83] = "CAN";
    arrayOfString[84] = "CAP";
    arrayOfString[85] = "CAR";
    arrayOfString[86] = "CAT";
    arrayOfString[87] = "CAW";
    arrayOfString[88] = "COD";
    arrayOfString[89] = "COG";
    arrayOfString[90] = "COL";
    arrayOfString[91] = "CON";
    arrayOfString[92] = "COO";
    arrayOfString[93] = "COP";
    arrayOfString[94] = "COT";
    arrayOfString[95] = "COW";
    arrayOfString[96] = "COY";
    arrayOfString[97] = "CRY";
    arrayOfString[98] = "CUB";
    arrayOfString[99] = "CUE";
    arrayOfString[100] = "CUP";
    arrayOfString[101] = "CUR";
    arrayOfString[102] = "CUT";
    arrayOfString[103] = "DAB";
    arrayOfString[104] = "DAD";
    arrayOfString[105] = "DAM";
    arrayOfString[106] = "DAN";
    arrayOfString[107] = "DAR";
    arrayOfString[108] = "DAY";
    arrayOfString[109] = "DEE";
    arrayOfString[110] = "DEL";
    arrayOfString[111] = "DEN";
    arrayOfString[112] = "DES";
    arrayOfString[113] = "DEW";
    arrayOfString[114] = "DID";
    arrayOfString[115] = "DIE";
    arrayOfString[116] = "DIG";
    arrayOfString[117] = "DIN";
    arrayOfString[118] = "DIP";
    arrayOfString[119] = "DO";
    arrayOfString[120] = "DOE";
    arrayOfString[121] = "DOG";
    arrayOfString[122] = "DON";
    arrayOfString[123] = "DOT";
    arrayOfString[124] = "DOW";
    arrayOfString[125] = "DRY";
    arrayOfString[126] = "DUB";
    arrayOfString[127] = "DUD";
    arrayOfString[''] = "DUE";
    arrayOfString[''] = "DUG";
    arrayOfString[''] = "DUN";
    arrayOfString[''] = "EAR";
    arrayOfString[''] = "EAT";
    arrayOfString[''] = "ED";
    arrayOfString[''] = "EEL";
    arrayOfString[''] = "EGG";
    arrayOfString[''] = "EGO";
    arrayOfString[''] = "ELI";
    arrayOfString[''] = "ELK";
    arrayOfString[''] = "ELM";
    arrayOfString[''] = "ELY";
    arrayOfString[''] = "EM";
    arrayOfString[''] = "END";
    arrayOfString[''] = "EST";
    arrayOfString[''] = "ETC";
    arrayOfString[''] = "EVA";
    arrayOfString[''] = "EVE";
    arrayOfString[''] = "EWE";
    arrayOfString[''] = "EYE";
    arrayOfString[''] = "FAD";
    arrayOfString[''] = "FAN";
    arrayOfString[''] = "FAR";
    arrayOfString[''] = "FAT";
    arrayOfString[''] = "FAY";
    arrayOfString[''] = "FED";
    arrayOfString[''] = "FEE";
    arrayOfString[''] = "FEW";
    arrayOfString[''] = "FIB";
    arrayOfString[''] = "FIG";
    arrayOfString[''] = "FIN";
    arrayOfString[' '] = "FIR";
    arrayOfString['¡'] = "FIT";
    arrayOfString['¢'] = "FLO";
    arrayOfString['£'] = "FLY";
    arrayOfString['¤'] = "FOE";
    arrayOfString['¥'] = "FOG";
    arrayOfString['¦'] = "FOR";
    arrayOfString['§'] = "FRY";
    arrayOfString['¨'] = "FUM";
    arrayOfString['©'] = "FUN";
    arrayOfString['ª'] = "FUR";
    arrayOfString['«'] = "GAB";
    arrayOfString['¬'] = "GAD";
    arrayOfString['­'] = "GAG";
    arrayOfString['®'] = "GAL";
    arrayOfString['¯'] = "GAM";
    arrayOfString['°'] = "GAP";
    arrayOfString['±'] = "GAS";
    arrayOfString['²'] = "GAY";
    arrayOfString['³'] = "GEE";
    arrayOfString['´'] = "GEL";
    arrayOfString['µ'] = "GEM";
    arrayOfString['¶'] = "GET";
    arrayOfString['·'] = "GIG";
    arrayOfString['¸'] = "GIL";
    arrayOfString['¹'] = "GIN";
    arrayOfString['º'] = "GO";
    arrayOfString['»'] = "GOT";
    arrayOfString['¼'] = "GUM";
    arrayOfString['½'] = "GUN";
    arrayOfString['¾'] = "GUS";
    arrayOfString['¿'] = "GUT";
    arrayOfString['À'] = "GUY";
    arrayOfString['Á'] = "GYM";
    arrayOfString['Â'] = "GYP";
    arrayOfString['Ã'] = "HA";
    arrayOfString['Ä'] = "HAD";
    arrayOfString['Å'] = "HAL";
    arrayOfString['Æ'] = "HAM";
    arrayOfString['Ç'] = "HAN";
    arrayOfString['È'] = "HAP";
    arrayOfString['É'] = "HAS";
    arrayOfString['Ê'] = "HAT";
    arrayOfString['Ë'] = "HAW";
    arrayOfString['Ì'] = "HAY";
    arrayOfString['Í'] = "HE";
    arrayOfString['Î'] = "HEM";
    arrayOfString['Ï'] = "HEN";
    arrayOfString['Ð'] = "HER";
    arrayOfString['Ñ'] = "HEW";
    arrayOfString['Ò'] = "HEY";
    arrayOfString['Ó'] = "HI";
    arrayOfString['Ô'] = "HID";
    arrayOfString['Õ'] = "HIM";
    arrayOfString['Ö'] = "HIP";
    arrayOfString['×'] = "HIS";
    arrayOfString['Ø'] = "HIT";
    arrayOfString['Ù'] = "HO";
    arrayOfString['Ú'] = "HOB";
    arrayOfString['Û'] = "HOC";
    arrayOfString['Ü'] = "HOE";
    arrayOfString['Ý'] = "HOG";
    arrayOfString['Þ'] = "HOP";
    arrayOfString['ß'] = "HOT";
    arrayOfString['à'] = "HOW";
    arrayOfString['á'] = "HUB";
    arrayOfString['â'] = "HUE";
    arrayOfString['ã'] = "HUG";
    arrayOfString['ä'] = "HUH";
    arrayOfString['å'] = "HUM";
    arrayOfString['æ'] = "HUT";
    arrayOfString['ç'] = "I";
    arrayOfString['è'] = "ICY";
    arrayOfString['é'] = "IDA";
    arrayOfString['ê'] = "IF";
    arrayOfString['ë'] = "IKE";
    arrayOfString['ì'] = "ILL";
    arrayOfString['í'] = "INK";
    arrayOfString['î'] = "INN";
    arrayOfString['ï'] = "IO";
    arrayOfString['ð'] = "ION";
    arrayOfString['ñ'] = "IQ";
    arrayOfString['ò'] = "IRA";
    arrayOfString['ó'] = "IRE";
    arrayOfString['ô'] = "IRK";
    arrayOfString['õ'] = "IS";
    arrayOfString['ö'] = "IT";
    arrayOfString['÷'] = "ITS";
    arrayOfString['ø'] = "IVY";
    arrayOfString['ù'] = "JAB";
    arrayOfString['ú'] = "JAG";
    arrayOfString['û'] = "JAM";
    arrayOfString['ü'] = "JAN";
    arrayOfString['ý'] = "JAR";
    arrayOfString['þ'] = "JAW";
    arrayOfString['ÿ'] = "JAY";
    arrayOfString['Ā'] = "JET";
    arrayOfString['ā'] = "JIG";
    arrayOfString['Ă'] = "JIM";
    arrayOfString['ă'] = "JO";
    arrayOfString['Ą'] = "JOB";
    arrayOfString['ą'] = "JOE";
    arrayOfString['Ć'] = "JOG";
    arrayOfString['ć'] = "JOT";
    arrayOfString['Ĉ'] = "JOY";
    arrayOfString['ĉ'] = "JUG";
    arrayOfString['Ċ'] = "JUT";
    arrayOfString['ċ'] = "KAY";
    arrayOfString['Č'] = "KEG";
    arrayOfString['č'] = "KEN";
    arrayOfString['Ď'] = "KEY";
    arrayOfString['ď'] = "KID";
    arrayOfString['Đ'] = "KIM";
    arrayOfString['đ'] = "KIN";
    arrayOfString['Ē'] = "KIT";
    arrayOfString['ē'] = "LA";
    arrayOfString['Ĕ'] = "LAB";
    arrayOfString['ĕ'] = "LAC";
    arrayOfString['Ė'] = "LAD";
    arrayOfString['ė'] = "LAG";
    arrayOfString['Ę'] = "LAM";
    arrayOfString['ę'] = "LAP";
    arrayOfString['Ě'] = "LAW";
    arrayOfString['ě'] = "LAY";
    arrayOfString['Ĝ'] = "LEA";
    arrayOfString['ĝ'] = "LED";
    arrayOfString['Ğ'] = "LEE";
    arrayOfString['ğ'] = "LEG";
    arrayOfString['Ġ'] = "LEN";
    arrayOfString['ġ'] = "LEO";
    arrayOfString['Ģ'] = "LET";
    arrayOfString['ģ'] = "LEW";
    arrayOfString['Ĥ'] = "LID";
    arrayOfString['ĥ'] = "LIE";
    arrayOfString['Ħ'] = "LIN";
    arrayOfString['ħ'] = "LIP";
    arrayOfString['Ĩ'] = "LIT";
    arrayOfString['ĩ'] = "LO";
    arrayOfString['Ī'] = "LOB";
    arrayOfString['ī'] = "LOG";
    arrayOfString['Ĭ'] = "LOP";
    arrayOfString['ĭ'] = "LOS";
    arrayOfString['Į'] = "LOT";
    arrayOfString['į'] = "LOU";
    arrayOfString['İ'] = "LOW";
    arrayOfString['ı'] = "LOY";
    arrayOfString['Ĳ'] = "LUG";
    arrayOfString['ĳ'] = "LYE";
    arrayOfString['Ĵ'] = "MA";
    arrayOfString['ĵ'] = "MAC";
    arrayOfString['Ķ'] = "MAD";
    arrayOfString['ķ'] = "MAE";
    arrayOfString['ĸ'] = "MAN";
    arrayOfString['Ĺ'] = "MAO";
    arrayOfString['ĺ'] = "MAP";
    arrayOfString['Ļ'] = "MAT";
    arrayOfString['ļ'] = "MAW";
    arrayOfString['Ľ'] = "MAY";
    arrayOfString['ľ'] = "ME";
    arrayOfString['Ŀ'] = "MEG";
    arrayOfString['ŀ'] = "MEL";
    arrayOfString['Ł'] = "MEN";
    arrayOfString['ł'] = "MET";
    arrayOfString['Ń'] = "MEW";
    arrayOfString['ń'] = "MID";
    arrayOfString['Ņ'] = "MIN";
    arrayOfString['ņ'] = "MIT";
    arrayOfString['Ň'] = "MOB";
    arrayOfString['ň'] = "MOD";
    arrayOfString['ŉ'] = "MOE";
    arrayOfString['Ŋ'] = "MOO";
    arrayOfString['ŋ'] = "MOP";
    arrayOfString['Ō'] = "MOS";
    arrayOfString['ō'] = "MOT";
    arrayOfString['Ŏ'] = "MOW";
    arrayOfString['ŏ'] = "MUD";
    arrayOfString['Ő'] = "MUG";
    arrayOfString['ő'] = "MUM";
    arrayOfString['Œ'] = "MY";
    arrayOfString['œ'] = "NAB";
    arrayOfString['Ŕ'] = "NAG";
    arrayOfString['ŕ'] = "NAN";
    arrayOfString['Ŗ'] = "NAP";
    arrayOfString['ŗ'] = "NAT";
    arrayOfString['Ř'] = "NAY";
    arrayOfString['ř'] = "NE";
    arrayOfString['Ś'] = "NED";
    arrayOfString['ś'] = "NEE";
    arrayOfString['Ŝ'] = "NET";
    arrayOfString['ŝ'] = "NEW";
    arrayOfString['Ş'] = "NIB";
    arrayOfString['ş'] = "NIL";
    arrayOfString['Š'] = "NIP";
    arrayOfString['š'] = "NIT";
    arrayOfString['Ţ'] = "NO";
    arrayOfString['ţ'] = "NOB";
    arrayOfString['Ť'] = "NOD";
    arrayOfString['ť'] = "NON";
    arrayOfString['Ŧ'] = "NOR";
    arrayOfString['ŧ'] = "NOT";
    arrayOfString['Ũ'] = "NOV";
    arrayOfString['ũ'] = "NOW";
    arrayOfString['Ū'] = "NU";
    arrayOfString['ū'] = "NUN";
    arrayOfString['Ŭ'] = "NUT";
    arrayOfString['ŭ'] = "O";
    arrayOfString['Ů'] = "OAF";
    arrayOfString['ů'] = "OAK";
    arrayOfString['Ű'] = "OAR";
    arrayOfString['ű'] = "OAT";
    arrayOfString['Ų'] = "ODD";
    arrayOfString['ų'] = "ODE";
    arrayOfString['Ŵ'] = "OF";
    arrayOfString['ŵ'] = "OFF";
    arrayOfString['Ŷ'] = "OFT";
    arrayOfString['ŷ'] = "OH";
    arrayOfString['Ÿ'] = "OIL";
    arrayOfString['Ź'] = "OK";
    arrayOfString['ź'] = "OLD";
    arrayOfString['Ż'] = "ON";
    arrayOfString['ż'] = "ONE";
    arrayOfString['Ž'] = "OR";
    arrayOfString['ž'] = "ORB";
    arrayOfString['ſ'] = "ORE";
    arrayOfString['ƀ'] = "ORR";
    arrayOfString['Ɓ'] = "OS";
    arrayOfString['Ƃ'] = "OTT";
    arrayOfString['ƃ'] = "OUR";
    arrayOfString['Ƅ'] = "OUT";
    arrayOfString['ƅ'] = "OVA";
    arrayOfString['Ɔ'] = "OW";
    arrayOfString['Ƈ'] = "OWE";
    arrayOfString['ƈ'] = "OWL";
    arrayOfString['Ɖ'] = "OWN";
    arrayOfString['Ɗ'] = "OX";
    arrayOfString['Ƌ'] = "PA";
    arrayOfString['ƌ'] = "PAD";
    arrayOfString['ƍ'] = "PAL";
    arrayOfString['Ǝ'] = "PAM";
    arrayOfString['Ə'] = "PAN";
    arrayOfString['Ɛ'] = "PAP";
    arrayOfString['Ƒ'] = "PAR";
    arrayOfString['ƒ'] = "PAT";
    arrayOfString['Ɠ'] = "PAW";
    arrayOfString['Ɣ'] = "PAY";
    arrayOfString['ƕ'] = "PEA";
    arrayOfString['Ɩ'] = "PEG";
    arrayOfString['Ɨ'] = "PEN";
    arrayOfString['Ƙ'] = "PEP";
    arrayOfString['ƙ'] = "PER";
    arrayOfString['ƚ'] = "PET";
    arrayOfString['ƛ'] = "PEW";
    arrayOfString['Ɯ'] = "PHI";
    arrayOfString['Ɲ'] = "PI";
    arrayOfString['ƞ'] = "PIE";
    arrayOfString['Ɵ'] = "PIN";
    arrayOfString['Ơ'] = "PIT";
    arrayOfString['ơ'] = "PLY";
    arrayOfString['Ƣ'] = "PO";
    arrayOfString['ƣ'] = "POD";
    arrayOfString['Ƥ'] = "POE";
    arrayOfString['ƥ'] = "POP";
    arrayOfString['Ʀ'] = "POT";
    arrayOfString['Ƨ'] = "POW";
    arrayOfString['ƨ'] = "PRO";
    arrayOfString['Ʃ'] = "PRY";
    arrayOfString['ƪ'] = "PUB";
    arrayOfString['ƫ'] = "PUG";
    arrayOfString['Ƭ'] = "PUN";
    arrayOfString['ƭ'] = "PUP";
    arrayOfString['Ʈ'] = "PUT";
    arrayOfString['Ư'] = "QUO";
    arrayOfString['ư'] = "RAG";
    arrayOfString['Ʊ'] = "RAM";
    arrayOfString['Ʋ'] = "RAN";
    arrayOfString['Ƴ'] = "RAP";
    arrayOfString['ƴ'] = "RAT";
    arrayOfString['Ƶ'] = "RAW";
    arrayOfString['ƶ'] = "RAY";
    arrayOfString['Ʒ'] = "REB";
    arrayOfString['Ƹ'] = "RED";
    arrayOfString['ƹ'] = "REP";
    arrayOfString['ƺ'] = "RET";
    arrayOfString['ƻ'] = "RIB";
    arrayOfString['Ƽ'] = "RID";
    arrayOfString['ƽ'] = "RIG";
    arrayOfString['ƾ'] = "RIM";
    arrayOfString['ƿ'] = "RIO";
    arrayOfString['ǀ'] = "RIP";
    arrayOfString['ǁ'] = "ROB";
    arrayOfString['ǂ'] = "ROD";
    arrayOfString['ǃ'] = "ROE";
    arrayOfString['Ǆ'] = "RON";
    arrayOfString['ǅ'] = "ROT";
    arrayOfString['ǆ'] = "ROW";
    arrayOfString['Ǉ'] = "ROY";
    arrayOfString['ǈ'] = "RUB";
    arrayOfString['ǉ'] = "RUE";
    arrayOfString['Ǌ'] = "RUG";
    arrayOfString['ǋ'] = "RUM";
    arrayOfString['ǌ'] = "RUN";
    arrayOfString['Ǎ'] = "RYE";
    arrayOfString['ǎ'] = "SAC";
    arrayOfString['Ǐ'] = "SAD";
    arrayOfString['ǐ'] = "SAG";
    arrayOfString['Ǒ'] = "SAL";
    arrayOfString['ǒ'] = "SAM";
    arrayOfString['Ǔ'] = "SAN";
    arrayOfString['ǔ'] = "SAP";
    arrayOfString['Ǖ'] = "SAT";
    arrayOfString['ǖ'] = "SAW";
    arrayOfString['Ǘ'] = "SAY";
    arrayOfString['ǘ'] = "SEA";
    arrayOfString['Ǚ'] = "SEC";
    arrayOfString['ǚ'] = "SEE";
    arrayOfString['Ǜ'] = "SEN";
    arrayOfString['ǜ'] = "SET";
    arrayOfString['ǝ'] = "SEW";
    arrayOfString['Ǟ'] = "SHE";
    arrayOfString['ǟ'] = "SHY";
    arrayOfString['Ǡ'] = "SIN";
    arrayOfString['ǡ'] = "SIP";
    arrayOfString['Ǣ'] = "SIR";
    arrayOfString['ǣ'] = "SIS";
    arrayOfString['Ǥ'] = "SIT";
    arrayOfString['ǥ'] = "SKI";
    arrayOfString['Ǧ'] = "SKY";
    arrayOfString['ǧ'] = "SLY";
    arrayOfString['Ǩ'] = "SO";
    arrayOfString['ǩ'] = "SOB";
    arrayOfString['Ǫ'] = "SOD";
    arrayOfString['ǫ'] = "SON";
    arrayOfString['Ǭ'] = "SOP";
    arrayOfString['ǭ'] = "SOW";
    arrayOfString['Ǯ'] = "SOY";
    arrayOfString['ǯ'] = "SPA";
    arrayOfString['ǰ'] = "SPY";
    arrayOfString['Ǳ'] = "SUB";
    arrayOfString['ǲ'] = "SUD";
    arrayOfString['ǳ'] = "SUE";
    arrayOfString['Ǵ'] = "SUM";
    arrayOfString['ǵ'] = "SUN";
    arrayOfString['Ƕ'] = "SUP";
    arrayOfString['Ƿ'] = "TAB";
    arrayOfString['Ǹ'] = "TAD";
    arrayOfString['ǹ'] = "TAG";
    arrayOfString['Ǻ'] = "TAN";
    arrayOfString['ǻ'] = "TAP";
    arrayOfString['Ǽ'] = "TAR";
    arrayOfString['ǽ'] = "TEA";
    arrayOfString['Ǿ'] = "TED";
    arrayOfString['ǿ'] = "TEE";
    arrayOfString['Ȁ'] = "TEN";
    arrayOfString['ȁ'] = "THE";
    arrayOfString['Ȃ'] = "THY";
    arrayOfString['ȃ'] = "TIC";
    arrayOfString['Ȅ'] = "TIE";
    arrayOfString['ȅ'] = "TIM";
    arrayOfString['Ȇ'] = "TIN";
    arrayOfString['ȇ'] = "TIP";
    arrayOfString['Ȉ'] = "TO";
    arrayOfString['ȉ'] = "TOE";
    arrayOfString['Ȋ'] = "TOG";
    arrayOfString['ȋ'] = "TOM";
    arrayOfString['Ȍ'] = "TON";
    arrayOfString['ȍ'] = "TOO";
    arrayOfString['Ȏ'] = "TOP";
    arrayOfString['ȏ'] = "TOW";
    arrayOfString['Ȑ'] = "TOY";
    arrayOfString['ȑ'] = "TRY";
    arrayOfString['Ȓ'] = "TUB";
    arrayOfString['ȓ'] = "TUG";
    arrayOfString['Ȕ'] = "TUM";
    arrayOfString['ȕ'] = "TUN";
    arrayOfString['Ȗ'] = "TWO";
    arrayOfString['ȗ'] = "UN";
    arrayOfString['Ș'] = "UP";
    arrayOfString['ș'] = "US";
    arrayOfString['Ț'] = "USE";
    arrayOfString['ț'] = "VAN";
    arrayOfString['Ȝ'] = "VAT";
    arrayOfString['ȝ'] = "VET";
    arrayOfString['Ȟ'] = "VIE";
    arrayOfString['ȟ'] = "WAD";
    arrayOfString['Ƞ'] = "WAG";
    arrayOfString['ȡ'] = "WAR";
    arrayOfString['Ȣ'] = "WAS";
    arrayOfString['ȣ'] = "WAY";
    arrayOfString['Ȥ'] = "WE";
    arrayOfString['ȥ'] = "WEB";
    arrayOfString['Ȧ'] = "WED";
    arrayOfString['ȧ'] = "WEE";
    arrayOfString['Ȩ'] = "WET";
    arrayOfString['ȩ'] = "WHO";
    arrayOfString['Ȫ'] = "WHY";
    arrayOfString['ȫ'] = "WIN";
    arrayOfString['Ȭ'] = "WIT";
    arrayOfString['ȭ'] = "WOK";
    arrayOfString['Ȯ'] = "WON";
    arrayOfString['ȯ'] = "WOO";
    arrayOfString['Ȱ'] = "WOW";
    arrayOfString['ȱ'] = "WRY";
    arrayOfString['Ȳ'] = "WU";
    arrayOfString['ȳ'] = "YAM";
    arrayOfString['ȴ'] = "YAP";
    arrayOfString['ȵ'] = "YAW";
    arrayOfString['ȶ'] = "YE";
    arrayOfString['ȷ'] = "YEA";
    arrayOfString['ȸ'] = "YES";
    arrayOfString['ȹ'] = "YET";
    arrayOfString['Ⱥ'] = "YOU";
    arrayOfString['Ȼ'] = "ABED";
    arrayOfString['ȼ'] = "ABEL";
    arrayOfString['Ƚ'] = "ABET";
    arrayOfString['Ⱦ'] = "ABLE";
    arrayOfString['ȿ'] = "ABUT";
    arrayOfString['ɀ'] = "ACHE";
    arrayOfString['Ɂ'] = "ACID";
    arrayOfString['ɂ'] = "ACME";
    arrayOfString['Ƀ'] = "ACRE";
    arrayOfString['Ʉ'] = "ACTA";
    arrayOfString['Ʌ'] = "ACTS";
    arrayOfString['Ɇ'] = "ADAM";
    arrayOfString['ɇ'] = "ADDS";
    arrayOfString['Ɉ'] = "ADEN";
    arrayOfString['ɉ'] = "AFAR";
    arrayOfString['Ɋ'] = "AFRO";
    arrayOfString['ɋ'] = "AGEE";
    arrayOfString['Ɍ'] = "AHEM";
    arrayOfString['ɍ'] = "AHOY";
    arrayOfString['Ɏ'] = "AIDA";
    arrayOfString['ɏ'] = "AIDE";
    arrayOfString['ɐ'] = "AIDS";
    arrayOfString['ɑ'] = "AIRY";
    arrayOfString['ɒ'] = "AJAR";
    arrayOfString['ɓ'] = "AKIN";
    arrayOfString['ɔ'] = "ALAN";
    arrayOfString['ɕ'] = "ALEC";
    arrayOfString['ɖ'] = "ALGA";
    arrayOfString['ɗ'] = "ALIA";
    arrayOfString['ɘ'] = "ALLY";
    arrayOfString['ə'] = "ALMA";
    arrayOfString['ɚ'] = "ALOE";
    arrayOfString['ɛ'] = "ALSO";
    arrayOfString['ɜ'] = "ALTO";
    arrayOfString['ɝ'] = "ALUM";
    arrayOfString['ɞ'] = "ALVA";
    arrayOfString['ɟ'] = "AMEN";
    arrayOfString['ɠ'] = "AMES";
    arrayOfString['ɡ'] = "AMID";
    arrayOfString['ɢ'] = "AMMO";
    arrayOfString['ɣ'] = "AMOK";
    arrayOfString['ɤ'] = "AMOS";
    arrayOfString['ɥ'] = "AMRA";
    arrayOfString['ɦ'] = "ANDY";
    arrayOfString['ɧ'] = "ANEW";
    arrayOfString['ɨ'] = "ANNA";
    arrayOfString['ɩ'] = "ANNE";
    arrayOfString['ɪ'] = "ANTE";
    arrayOfString['ɫ'] = "ANTI";
    arrayOfString['ɬ'] = "AQUA";
    arrayOfString['ɭ'] = "ARAB";
    arrayOfString['ɮ'] = "ARCH";
    arrayOfString['ɯ'] = "AREA";
    arrayOfString['ɰ'] = "ARGO";
    arrayOfString['ɱ'] = "ARID";
    arrayOfString['ɲ'] = "ARMY";
    arrayOfString['ɳ'] = "ARTS";
    arrayOfString['ɴ'] = "ARTY";
    arrayOfString['ɵ'] = "ASIA";
    arrayOfString['ɶ'] = "ASKS";
    arrayOfString['ɷ'] = "ATOM";
    arrayOfString['ɸ'] = "AUNT";
    arrayOfString['ɹ'] = "AURA";
    arrayOfString['ɺ'] = "AUTO";
    arrayOfString['ɻ'] = "AVER";
    arrayOfString['ɼ'] = "AVID";
    arrayOfString['ɽ'] = "AVIS";
    arrayOfString['ɾ'] = "AVON";
    arrayOfString['ɿ'] = "AVOW";
    arrayOfString['ʀ'] = "AWAY";
    arrayOfString['ʁ'] = "AWRY";
    arrayOfString['ʂ'] = "BABE";
    arrayOfString['ʃ'] = "BABY";
    arrayOfString['ʄ'] = "BACH";
    arrayOfString['ʅ'] = "BACK";
    arrayOfString['ʆ'] = "BADE";
    arrayOfString['ʇ'] = "BAIL";
    arrayOfString['ʈ'] = "BAIT";
    arrayOfString['ʉ'] = "BAKE";
    arrayOfString['ʊ'] = "BALD";
    arrayOfString['ʋ'] = "BALE";
    arrayOfString['ʌ'] = "BALI";
    arrayOfString['ʍ'] = "BALK";
    arrayOfString['ʎ'] = "BALL";
    arrayOfString['ʏ'] = "BALM";
    arrayOfString['ʐ'] = "BAND";
    arrayOfString['ʑ'] = "BANE";
    arrayOfString['ʒ'] = "BANG";
    arrayOfString['ʓ'] = "BANK";
    arrayOfString['ʔ'] = "BARB";
    arrayOfString['ʕ'] = "BARD";
    arrayOfString['ʖ'] = "BARE";
    arrayOfString['ʗ'] = "BARK";
    arrayOfString['ʘ'] = "BARN";
    arrayOfString['ʙ'] = "BARR";
    arrayOfString['ʚ'] = "BASE";
    arrayOfString['ʛ'] = "BASH";
    arrayOfString['ʜ'] = "BASK";
    arrayOfString['ʝ'] = "BASS";
    arrayOfString['ʞ'] = "BATE";
    arrayOfString['ʟ'] = "BATH";
    arrayOfString['ʠ'] = "BAWD";
    arrayOfString['ʡ'] = "BAWL";
    arrayOfString['ʢ'] = "BEAD";
    arrayOfString['ʣ'] = "BEAK";
    arrayOfString['ʤ'] = "BEAM";
    arrayOfString['ʥ'] = "BEAN";
    arrayOfString['ʦ'] = "BEAR";
    arrayOfString['ʧ'] = "BEAT";
    arrayOfString['ʨ'] = "BEAU";
    arrayOfString['ʩ'] = "BECK";
    arrayOfString['ʪ'] = "BEEF";
    arrayOfString['ʫ'] = "BEEN";
    arrayOfString['ʬ'] = "BEER";
    arrayOfString['ʭ'] = "BEET";
    arrayOfString['ʮ'] = "BELA";
    arrayOfString['ʯ'] = "BELL";
    arrayOfString['ʰ'] = "BELT";
    arrayOfString['ʱ'] = "BEND";
    arrayOfString['ʲ'] = "BENT";
    arrayOfString['ʳ'] = "BERG";
    arrayOfString['ʴ'] = "BERN";
    arrayOfString['ʵ'] = "BERT";
    arrayOfString['ʶ'] = "BESS";
    arrayOfString['ʷ'] = "BEST";
    arrayOfString['ʸ'] = "BETA";
    arrayOfString['ʹ'] = "BETH";
    arrayOfString['ʺ'] = "BHOY";
    arrayOfString['ʻ'] = "BIAS";
    arrayOfString['ʼ'] = "BIDE";
    arrayOfString['ʽ'] = "BIEN";
    arrayOfString['ʾ'] = "BILE";
    arrayOfString['ʿ'] = "BILK";
    arrayOfString['ˀ'] = "BILL";
    arrayOfString['ˁ'] = "BIND";
    arrayOfString['˂'] = "BING";
    arrayOfString['˃'] = "BIRD";
    arrayOfString['˄'] = "BITE";
    arrayOfString['˅'] = "BITS";
    arrayOfString['ˆ'] = "BLAB";
    arrayOfString['ˇ'] = "BLAT";
    arrayOfString['ˈ'] = "BLED";
    arrayOfString['ˉ'] = "BLEW";
    arrayOfString['ˊ'] = "BLOB";
    arrayOfString['ˋ'] = "BLOC";
    arrayOfString['ˌ'] = "BLOT";
    arrayOfString['ˍ'] = "BLOW";
    arrayOfString['ˎ'] = "BLUE";
    arrayOfString['ˏ'] = "BLUM";
    arrayOfString['ː'] = "BLUR";
    arrayOfString['ˑ'] = "BOAR";
    arrayOfString['˒'] = "BOAT";
    arrayOfString['˓'] = "BOCA";
    arrayOfString['˔'] = "BOCK";
    arrayOfString['˕'] = "BODE";
    arrayOfString['˖'] = "BODY";
    arrayOfString['˗'] = "BOGY";
    arrayOfString['˘'] = "BOHR";
    arrayOfString['˙'] = "BOIL";
    arrayOfString['˚'] = "BOLD";
    arrayOfString['˛'] = "BOLO";
    arrayOfString['˜'] = "BOLT";
    arrayOfString['˝'] = "BOMB";
    arrayOfString['˞'] = "BONA";
    arrayOfString['˟'] = "BOND";
    arrayOfString['ˠ'] = "BONE";
    arrayOfString['ˡ'] = "BONG";
    arrayOfString['ˢ'] = "BONN";
    arrayOfString['ˣ'] = "BONY";
    arrayOfString['ˤ'] = "BOOK";
    arrayOfString['˥'] = "BOOM";
    arrayOfString['˦'] = "BOON";
    arrayOfString['˧'] = "BOOT";
    arrayOfString['˨'] = "BORE";
    arrayOfString['˩'] = "BORG";
    arrayOfString['˪'] = "BORN";
    arrayOfString['˫'] = "BOSE";
    arrayOfString['ˬ'] = "BOSS";
    arrayOfString['˭'] = "BOTH";
    arrayOfString['ˮ'] = "BOUT";
    arrayOfString['˯'] = "BOWL";
    arrayOfString['˰'] = "BOYD";
    arrayOfString['˱'] = "BRAD";
    arrayOfString['˲'] = "BRAE";
    arrayOfString['˳'] = "BRAG";
    arrayOfString['˴'] = "BRAN";
    arrayOfString['˵'] = "BRAY";
    arrayOfString['˶'] = "BRED";
    arrayOfString['˷'] = "BREW";
    arrayOfString['˸'] = "BRIG";
    arrayOfString['˹'] = "BRIM";
    arrayOfString['˺'] = "BROW";
    arrayOfString['˻'] = "BUCK";
    arrayOfString['˼'] = "BUDD";
    arrayOfString['˽'] = "BUFF";
    arrayOfString['˾'] = "BULB";
    arrayOfString['˿'] = "BULK";
    arrayOfString['̀'] = "BULL";
    arrayOfString['́'] = "BUNK";
    arrayOfString['̂'] = "BUNT";
    arrayOfString['̃'] = "BUOY";
    arrayOfString['̄'] = "BURG";
    arrayOfString['̅'] = "BURL";
    arrayOfString['̆'] = "BURN";
    arrayOfString['̇'] = "BURR";
    arrayOfString['̈'] = "BURT";
    arrayOfString['̉'] = "BURY";
    arrayOfString['̊'] = "BUSH";
    arrayOfString['̋'] = "BUSS";
    arrayOfString['̌'] = "BUST";
    arrayOfString['̍'] = "BUSY";
    arrayOfString['̎'] = "BYTE";
    arrayOfString['̏'] = "CADY";
    arrayOfString['̐'] = "CAFE";
    arrayOfString['̑'] = "CAGE";
    arrayOfString['̒'] = "CAIN";
    arrayOfString['̓'] = "CAKE";
    arrayOfString['̔'] = "CALF";
    arrayOfString['̕'] = "CALL";
    arrayOfString['̖'] = "CALM";
    arrayOfString['̗'] = "CAME";
    arrayOfString['̘'] = "CANE";
    arrayOfString['̙'] = "CANT";
    arrayOfString['̚'] = "CARD";
    arrayOfString['̛'] = "CARE";
    arrayOfString['̜'] = "CARL";
    arrayOfString['̝'] = "CARR";
    arrayOfString['̞'] = "CART";
    arrayOfString['̟'] = "CASE";
    arrayOfString['̠'] = "CASH";
    arrayOfString['̡'] = "CASK";
    arrayOfString['̢'] = "CAST";
    arrayOfString['̣'] = "CAVE";
    arrayOfString['̤'] = "CEIL";
    arrayOfString['̥'] = "CELL";
    arrayOfString['̦'] = "CENT";
    arrayOfString['̧'] = "CERN";
    arrayOfString['̨'] = "CHAD";
    arrayOfString['̩'] = "CHAR";
    arrayOfString['̪'] = "CHAT";
    arrayOfString['̫'] = "CHAW";
    arrayOfString['̬'] = "CHEF";
    arrayOfString['̭'] = "CHEN";
    arrayOfString['̮'] = "CHEW";
    arrayOfString['̯'] = "CHIC";
    arrayOfString['̰'] = "CHIN";
    arrayOfString['̱'] = "CHOU";
    arrayOfString['̲'] = "CHOW";
    arrayOfString['̳'] = "CHUB";
    arrayOfString['̴'] = "CHUG";
    arrayOfString['̵'] = "CHUM";
    arrayOfString['̶'] = "CITE";
    arrayOfString['̷'] = "CITY";
    arrayOfString['̸'] = "CLAD";
    arrayOfString['̹'] = "CLAM";
    arrayOfString['̺'] = "CLAN";
    arrayOfString['̻'] = "CLAW";
    arrayOfString['̼'] = "CLAY";
    arrayOfString['̽'] = "CLOD";
    arrayOfString['̾'] = "CLOG";
    arrayOfString['̿'] = "CLOT";
    arrayOfString['̀'] = "CLUB";
    arrayOfString['́'] = "CLUE";
    arrayOfString['͂'] = "COAL";
    arrayOfString['̓'] = "COAT";
    arrayOfString['̈́'] = "COCA";
    arrayOfString['ͅ'] = "COCK";
    arrayOfString['͆'] = "COCO";
    arrayOfString['͇'] = "CODA";
    arrayOfString['͈'] = "CODE";
    arrayOfString['͉'] = "CODY";
    arrayOfString['͊'] = "COED";
    arrayOfString['͋'] = "COIL";
    arrayOfString['͌'] = "COIN";
    arrayOfString['͍'] = "COKE";
    arrayOfString['͎'] = "COLA";
    arrayOfString['͏'] = "COLD";
    arrayOfString['͐'] = "COLT";
    arrayOfString['͑'] = "COMA";
    arrayOfString['͒'] = "COMB";
    arrayOfString['͓'] = "COME";
    arrayOfString['͔'] = "COOK";
    arrayOfString['͕'] = "COOL";
    arrayOfString['͖'] = "COON";
    arrayOfString['͗'] = "COOT";
    arrayOfString['͘'] = "CORD";
    arrayOfString['͙'] = "CORE";
    arrayOfString['͚'] = "CORK";
    arrayOfString['͛'] = "CORN";
    arrayOfString['͜'] = "COST";
    arrayOfString['͝'] = "COVE";
    arrayOfString['͞'] = "COWL";
    arrayOfString['͟'] = "CRAB";
    arrayOfString['͠'] = "CRAG";
    arrayOfString['͡'] = "CRAM";
    arrayOfString['͢'] = "CRAY";
    arrayOfString['ͣ'] = "CREW";
    arrayOfString['ͤ'] = "CRIB";
    arrayOfString['ͥ'] = "CROW";
    arrayOfString['ͦ'] = "CRUD";
    arrayOfString['ͧ'] = "CUBA";
    arrayOfString['ͨ'] = "CUBE";
    arrayOfString['ͩ'] = "CUFF";
    arrayOfString['ͪ'] = "CULL";
    arrayOfString['ͫ'] = "CULT";
    arrayOfString['ͬ'] = "CUNY";
    arrayOfString['ͭ'] = "CURB";
    arrayOfString['ͮ'] = "CURD";
    arrayOfString['ͯ'] = "CURE";
    arrayOfString['Ͱ'] = "CURL";
    arrayOfString['ͱ'] = "CURT";
    arrayOfString['Ͳ'] = "CUTS";
    arrayOfString['ͳ'] = "DADE";
    arrayOfString['ʹ'] = "DALE";
    arrayOfString['͵'] = "DAME";
    arrayOfString['Ͷ'] = "DANA";
    arrayOfString['ͷ'] = "DANE";
    arrayOfString['͸'] = "DANG";
    arrayOfString['͹'] = "DANK";
    arrayOfString['ͺ'] = "DARE";
    arrayOfString['ͻ'] = "DARK";
    arrayOfString['ͼ'] = "DARN";
    arrayOfString['ͽ'] = "DART";
    arrayOfString[';'] = "DASH";
    arrayOfString['Ϳ'] = "DATA";
    arrayOfString['΀'] = "DATE";
    arrayOfString['΁'] = "DAVE";
    arrayOfString['΂'] = "DAVY";
    arrayOfString['΃'] = "DAWN";
    arrayOfString['΄'] = "DAYS";
    arrayOfString['΅'] = "DEAD";
    arrayOfString['Ά'] = "DEAF";
    arrayOfString['·'] = "DEAL";
    arrayOfString['Έ'] = "DEAN";
    arrayOfString['Ή'] = "DEAR";
    arrayOfString['Ί'] = "DEBT";
    arrayOfString['΋'] = "DECK";
    arrayOfString['Ό'] = "DEED";
    arrayOfString['΍'] = "DEEM";
    arrayOfString['Ύ'] = "DEER";
    arrayOfString['Ώ'] = "DEFT";
    arrayOfString['ΐ'] = "DEFY";
    arrayOfString['Α'] = "DELL";
    arrayOfString['Β'] = "DENT";
    arrayOfString['Γ'] = "DENY";
    arrayOfString['Δ'] = "DESK";
    arrayOfString['Ε'] = "DIAL";
    arrayOfString['Ζ'] = "DICE";
    arrayOfString['Η'] = "DIED";
    arrayOfString['Θ'] = "DIET";
    arrayOfString['Ι'] = "DIME";
    arrayOfString['Κ'] = "DINE";
    arrayOfString['Λ'] = "DING";
    arrayOfString['Μ'] = "DINT";
    arrayOfString['Ν'] = "DIRE";
    arrayOfString['Ξ'] = "DIRT";
    arrayOfString['Ο'] = "DISC";
    arrayOfString['Π'] = "DISH";
    arrayOfString['Ρ'] = "DISK";
    arrayOfString['΢'] = "DIVE";
    arrayOfString['Σ'] = "DOCK";
    arrayOfString['Τ'] = "DOES";
    arrayOfString['Υ'] = "DOLE";
    arrayOfString['Φ'] = "DOLL";
    arrayOfString['Χ'] = "DOLT";
    arrayOfString['Ψ'] = "DOME";
    arrayOfString['Ω'] = "DONE";
    arrayOfString['Ϊ'] = "DOOM";
    arrayOfString['Ϋ'] = "DOOR";
    arrayOfString['ά'] = "DORA";
    arrayOfString['έ'] = "DOSE";
    arrayOfString['ή'] = "DOTE";
    arrayOfString['ί'] = "DOUG";
    arrayOfString['ΰ'] = "DOUR";
    arrayOfString['α'] = "DOVE";
    arrayOfString['β'] = "DOWN";
    arrayOfString['γ'] = "DRAB";
    arrayOfString['δ'] = "DRAG";
    arrayOfString['ε'] = "DRAM";
    arrayOfString['ζ'] = "DRAW";
    arrayOfString['η'] = "DREW";
    arrayOfString['θ'] = "DRUB";
    arrayOfString['ι'] = "DRUG";
    arrayOfString['κ'] = "DRUM";
    arrayOfString['λ'] = "DUAL";
    arrayOfString['μ'] = "DUCK";
    arrayOfString['ν'] = "DUCT";
    arrayOfString['ξ'] = "DUEL";
    arrayOfString['ο'] = "DUET";
    arrayOfString['π'] = "DUKE";
    arrayOfString['ρ'] = "DULL";
    arrayOfString['ς'] = "DUMB";
    arrayOfString['σ'] = "DUNE";
    arrayOfString['τ'] = "DUNK";
    arrayOfString['υ'] = "DUSK";
    arrayOfString['φ'] = "DUST";
    arrayOfString['χ'] = "DUTY";
    arrayOfString['ψ'] = "EACH";
    arrayOfString['ω'] = "EARL";
    arrayOfString['ϊ'] = "EARN";
    arrayOfString['ϋ'] = "EASE";
    arrayOfString['ό'] = "EAST";
    arrayOfString['ύ'] = "EASY";
    arrayOfString['ώ'] = "EBEN";
    arrayOfString['Ϗ'] = "ECHO";
    arrayOfString['ϐ'] = "EDDY";
    arrayOfString['ϑ'] = "EDEN";
    arrayOfString['ϒ'] = "EDGE";
    arrayOfString['ϓ'] = "EDGY";
    arrayOfString['ϔ'] = "EDIT";
    arrayOfString['ϕ'] = "EDNA";
    arrayOfString['ϖ'] = "EGAN";
    arrayOfString['ϗ'] = "ELAN";
    arrayOfString['Ϙ'] = "ELBA";
    arrayOfString['ϙ'] = "ELLA";
    arrayOfString['Ϛ'] = "ELSE";
    arrayOfString['ϛ'] = "EMIL";
    arrayOfString['Ϝ'] = "EMIT";
    arrayOfString['ϝ'] = "EMMA";
    arrayOfString['Ϟ'] = "ENDS";
    arrayOfString['ϟ'] = "ERIC";
    arrayOfString['Ϡ'] = "EROS";
    arrayOfString['ϡ'] = "EVEN";
    arrayOfString['Ϣ'] = "EVER";
    arrayOfString['ϣ'] = "EVIL";
    arrayOfString['Ϥ'] = "EYED";
    arrayOfString['ϥ'] = "FACE";
    arrayOfString['Ϧ'] = "FACT";
    arrayOfString['ϧ'] = "FADE";
    arrayOfString['Ϩ'] = "FAIL";
    arrayOfString['ϩ'] = "FAIN";
    arrayOfString['Ϫ'] = "FAIR";
    arrayOfString['ϫ'] = "FAKE";
    arrayOfString['Ϭ'] = "FALL";
    arrayOfString['ϭ'] = "FAME";
    arrayOfString['Ϯ'] = "FANG";
    arrayOfString['ϯ'] = "FARM";
    arrayOfString['ϰ'] = "FAST";
    arrayOfString['ϱ'] = "FATE";
    arrayOfString['ϲ'] = "FAWN";
    arrayOfString['ϳ'] = "FEAR";
    arrayOfString['ϴ'] = "FEAT";
    arrayOfString['ϵ'] = "FEED";
    arrayOfString['϶'] = "FEEL";
    arrayOfString['Ϸ'] = "FEET";
    arrayOfString['ϸ'] = "FELL";
    arrayOfString['Ϲ'] = "FELT";
    arrayOfString['Ϻ'] = "FEND";
    arrayOfString['ϻ'] = "FERN";
    arrayOfString['ϼ'] = "FEST";
    arrayOfString['Ͻ'] = "FEUD";
    arrayOfString['Ͼ'] = "FIEF";
    arrayOfString['Ͽ'] = "FIGS";
    arrayOfString['Ѐ'] = "FILE";
    arrayOfString['Ё'] = "FILL";
    arrayOfString['Ђ'] = "FILM";
    arrayOfString['Ѓ'] = "FIND";
    arrayOfString['Є'] = "FINE";
    arrayOfString['Ѕ'] = "FINK";
    arrayOfString['І'] = "FIRE";
    arrayOfString['Ї'] = "FIRM";
    arrayOfString['Ј'] = "FISH";
    arrayOfString['Љ'] = "FISK";
    arrayOfString['Њ'] = "FIST";
    arrayOfString['Ћ'] = "FITS";
    arrayOfString['Ќ'] = "FIVE";
    arrayOfString['Ѝ'] = "FLAG";
    arrayOfString['Ў'] = "FLAK";
    arrayOfString['Џ'] = "FLAM";
    arrayOfString['А'] = "FLAT";
    arrayOfString['Б'] = "FLAW";
    arrayOfString['В'] = "FLEA";
    arrayOfString['Г'] = "FLED";
    arrayOfString['Д'] = "FLEW";
    arrayOfString['Е'] = "FLIT";
    arrayOfString['Ж'] = "FLOC";
    arrayOfString['З'] = "FLOG";
    arrayOfString['И'] = "FLOW";
    arrayOfString['Й'] = "FLUB";
    arrayOfString['К'] = "FLUE";
    arrayOfString['Л'] = "FOAL";
    arrayOfString['М'] = "FOAM";
    arrayOfString['Н'] = "FOGY";
    arrayOfString['О'] = "FOIL";
    arrayOfString['П'] = "FOLD";
    arrayOfString['Р'] = "FOLK";
    arrayOfString['С'] = "FOND";
    arrayOfString['Т'] = "FONT";
    arrayOfString['У'] = "FOOD";
    arrayOfString['Ф'] = "FOOL";
    arrayOfString['Х'] = "FOOT";
    arrayOfString['Ц'] = "FORD";
    arrayOfString['Ч'] = "FORE";
    arrayOfString['Ш'] = "FORK";
    arrayOfString['Щ'] = "FORM";
    arrayOfString['Ъ'] = "FORT";
    arrayOfString['Ы'] = "FOSS";
    arrayOfString['Ь'] = "FOUL";
    arrayOfString['Э'] = "FOUR";
    arrayOfString['Ю'] = "FOWL";
    arrayOfString['Я'] = "FRAU";
    arrayOfString['а'] = "FRAY";
    arrayOfString['б'] = "FRED";
    arrayOfString['в'] = "FREE";
    arrayOfString['г'] = "FRET";
    arrayOfString['д'] = "FREY";
    arrayOfString['е'] = "FROG";
    arrayOfString['ж'] = "FROM";
    arrayOfString['з'] = "FUEL";
    arrayOfString['и'] = "FULL";
    arrayOfString['й'] = "FUME";
    arrayOfString['к'] = "FUND";
    arrayOfString['л'] = "FUNK";
    arrayOfString['м'] = "FURY";
    arrayOfString['н'] = "FUSE";
    arrayOfString['о'] = "FUSS";
    arrayOfString['п'] = "GAFF";
    arrayOfString['р'] = "GAGE";
    arrayOfString['с'] = "GAIL";
    arrayOfString['т'] = "GAIN";
    arrayOfString['у'] = "GAIT";
    arrayOfString['ф'] = "GALA";
    arrayOfString['х'] = "GALE";
    arrayOfString['ц'] = "GALL";
    arrayOfString['ч'] = "GALT";
    arrayOfString['ш'] = "GAME";
    arrayOfString['щ'] = "GANG";
    arrayOfString['ъ'] = "GARB";
    arrayOfString['ы'] = "GARY";
    arrayOfString['ь'] = "GASH";
    arrayOfString['э'] = "GATE";
    arrayOfString['ю'] = "GAUL";
    arrayOfString['я'] = "GAUR";
    arrayOfString['ѐ'] = "GAVE";
    arrayOfString['ё'] = "GAWK";
    arrayOfString['ђ'] = "GEAR";
    arrayOfString['ѓ'] = "GELD";
    arrayOfString['є'] = "GENE";
    arrayOfString['ѕ'] = "GENT";
    arrayOfString['і'] = "GERM";
    arrayOfString['ї'] = "GETS";
    arrayOfString['ј'] = "GIBE";
    arrayOfString['љ'] = "GIFT";
    arrayOfString['њ'] = "GILD";
    arrayOfString['ћ'] = "GILL";
    arrayOfString['ќ'] = "GILT";
    arrayOfString['ѝ'] = "GINA";
    arrayOfString['ў'] = "GIRD";
    arrayOfString['џ'] = "GIRL";
    arrayOfString['Ѡ'] = "GIST";
    arrayOfString['ѡ'] = "GIVE";
    arrayOfString['Ѣ'] = "GLAD";
    arrayOfString['ѣ'] = "GLEE";
    arrayOfString['Ѥ'] = "GLEN";
    arrayOfString['ѥ'] = "GLIB";
    arrayOfString['Ѧ'] = "GLOB";
    arrayOfString['ѧ'] = "GLOM";
    arrayOfString['Ѩ'] = "GLOW";
    arrayOfString['ѩ'] = "GLUE";
    arrayOfString['Ѫ'] = "GLUM";
    arrayOfString['ѫ'] = "GLUT";
    arrayOfString['Ѭ'] = "GOAD";
    arrayOfString['ѭ'] = "GOAL";
    arrayOfString['Ѯ'] = "GOAT";
    arrayOfString['ѯ'] = "GOER";
    arrayOfString['Ѱ'] = "GOES";
    arrayOfString['ѱ'] = "GOLD";
    arrayOfString['Ѳ'] = "GOLF";
    arrayOfString['ѳ'] = "GONE";
    arrayOfString['Ѵ'] = "GONG";
    arrayOfString['ѵ'] = "GOOD";
    arrayOfString['Ѷ'] = "GOOF";
    arrayOfString['ѷ'] = "GORE";
    arrayOfString['Ѹ'] = "GORY";
    arrayOfString['ѹ'] = "GOSH";
    arrayOfString['Ѻ'] = "GOUT";
    arrayOfString['ѻ'] = "GOWN";
    arrayOfString['Ѽ'] = "GRAB";
    arrayOfString['ѽ'] = "GRAD";
    arrayOfString['Ѿ'] = "GRAY";
    arrayOfString['ѿ'] = "GREG";
    arrayOfString['Ҁ'] = "GREW";
    arrayOfString['ҁ'] = "GREY";
    arrayOfString['҂'] = "GRID";
    arrayOfString['҃'] = "GRIM";
    arrayOfString['҄'] = "GRIN";
    arrayOfString['҅'] = "GRIT";
    arrayOfString['҆'] = "GROW";
    arrayOfString['҇'] = "GRUB";
    arrayOfString['҈'] = "GULF";
    arrayOfString['҉'] = "GULL";
    arrayOfString['Ҋ'] = "GUNK";
    arrayOfString['ҋ'] = "GURU";
    arrayOfString['Ҍ'] = "GUSH";
    arrayOfString['ҍ'] = "GUST";
    arrayOfString['Ҏ'] = "GWEN";
    arrayOfString['ҏ'] = "GWYN";
    arrayOfString['Ґ'] = "HAAG";
    arrayOfString['ґ'] = "HAAS";
    arrayOfString['Ғ'] = "HACK";
    arrayOfString['ғ'] = "HAIL";
    arrayOfString['Ҕ'] = "HAIR";
    arrayOfString['ҕ'] = "HALE";
    arrayOfString['Җ'] = "HALF";
    arrayOfString['җ'] = "HALL";
    arrayOfString['Ҙ'] = "HALO";
    arrayOfString['ҙ'] = "HALT";
    arrayOfString['Қ'] = "HAND";
    arrayOfString['қ'] = "HANG";
    arrayOfString['Ҝ'] = "HANK";
    arrayOfString['ҝ'] = "HANS";
    arrayOfString['Ҟ'] = "HARD";
    arrayOfString['ҟ'] = "HARK";
    arrayOfString['Ҡ'] = "HARM";
    arrayOfString['ҡ'] = "HART";
    arrayOfString['Ң'] = "HASH";
    arrayOfString['ң'] = "HAST";
    arrayOfString['Ҥ'] = "HATE";
    arrayOfString['ҥ'] = "HATH";
    arrayOfString['Ҧ'] = "HAUL";
    arrayOfString['ҧ'] = "HAVE";
    arrayOfString['Ҩ'] = "HAWK";
    arrayOfString['ҩ'] = "HAYS";
    arrayOfString['Ҫ'] = "HEAD";
    arrayOfString['ҫ'] = "HEAL";
    arrayOfString['Ҭ'] = "HEAR";
    arrayOfString['ҭ'] = "HEAT";
    arrayOfString['Ү'] = "HEBE";
    arrayOfString['ү'] = "HECK";
    arrayOfString['Ұ'] = "HEED";
    arrayOfString['ұ'] = "HEEL";
    arrayOfString['Ҳ'] = "HEFT";
    arrayOfString['ҳ'] = "HELD";
    arrayOfString['Ҵ'] = "HELL";
    arrayOfString['ҵ'] = "HELM";
    arrayOfString['Ҷ'] = "HERB";
    arrayOfString['ҷ'] = "HERD";
    arrayOfString['Ҹ'] = "HERE";
    arrayOfString['ҹ'] = "HERO";
    arrayOfString['Һ'] = "HERS";
    arrayOfString['һ'] = "HESS";
    arrayOfString['Ҽ'] = "HEWN";
    arrayOfString['ҽ'] = "HICK";
    arrayOfString['Ҿ'] = "HIDE";
    arrayOfString['ҿ'] = "HIGH";
    arrayOfString['Ӏ'] = "HIKE";
    arrayOfString['Ӂ'] = "HILL";
    arrayOfString['ӂ'] = "HILT";
    arrayOfString['Ӄ'] = "HIND";
    arrayOfString['ӄ'] = "HINT";
    arrayOfString['Ӆ'] = "HIRE";
    arrayOfString['ӆ'] = "HISS";
    arrayOfString['Ӈ'] = "HIVE";
    arrayOfString['ӈ'] = "HOBO";
    arrayOfString['Ӊ'] = "HOCK";
    arrayOfString['ӊ'] = "HOFF";
    arrayOfString['Ӌ'] = "HOLD";
    arrayOfString['ӌ'] = "HOLE";
    arrayOfString['Ӎ'] = "HOLM";
    arrayOfString['ӎ'] = "HOLT";
    arrayOfString['ӏ'] = "HOME";
    arrayOfString['Ӑ'] = "HONE";
    arrayOfString['ӑ'] = "HONK";
    arrayOfString['Ӓ'] = "HOOD";
    arrayOfString['ӓ'] = "HOOF";
    arrayOfString['Ӕ'] = "HOOK";
    arrayOfString['ӕ'] = "HOOT";
    arrayOfString['Ӗ'] = "HORN";
    arrayOfString['ӗ'] = "HOSE";
    arrayOfString['Ә'] = "HOST";
    arrayOfString['ә'] = "HOUR";
    arrayOfString['Ӛ'] = "HOVE";
    arrayOfString['ӛ'] = "HOWE";
    arrayOfString['Ӝ'] = "HOWL";
    arrayOfString['ӝ'] = "HOYT";
    arrayOfString['Ӟ'] = "HUCK";
    arrayOfString['ӟ'] = "HUED";
    arrayOfString['Ӡ'] = "HUFF";
    arrayOfString['ӡ'] = "HUGE";
    arrayOfString['Ӣ'] = "HUGH";
    arrayOfString['ӣ'] = "HUGO";
    arrayOfString['Ӥ'] = "HULK";
    arrayOfString['ӥ'] = "HULL";
    arrayOfString['Ӧ'] = "HUNK";
    arrayOfString['ӧ'] = "HUNT";
    arrayOfString['Ө'] = "HURD";
    arrayOfString['ө'] = "HURL";
    arrayOfString['Ӫ'] = "HURT";
    arrayOfString['ӫ'] = "HUSH";
    arrayOfString['Ӭ'] = "HYDE";
    arrayOfString['ӭ'] = "HYMN";
    arrayOfString['Ӯ'] = "IBIS";
    arrayOfString['ӯ'] = "ICON";
    arrayOfString['Ӱ'] = "IDEA";
    arrayOfString['ӱ'] = "IDLE";
    arrayOfString['Ӳ'] = "IFFY";
    arrayOfString['ӳ'] = "INCA";
    arrayOfString['Ӵ'] = "INCH";
    arrayOfString['ӵ'] = "INTO";
    arrayOfString['Ӷ'] = "IONS";
    arrayOfString['ӷ'] = "IOTA";
    arrayOfString['Ӹ'] = "IOWA";
    arrayOfString['ӹ'] = "IRIS";
    arrayOfString['Ӻ'] = "IRMA";
    arrayOfString['ӻ'] = "IRON";
    arrayOfString['Ӽ'] = "ISLE";
    arrayOfString['ӽ'] = "ITCH";
    arrayOfString['Ӿ'] = "ITEM";
    arrayOfString['ӿ'] = "IVAN";
    arrayOfString['Ԁ'] = "JACK";
    arrayOfString['ԁ'] = "JADE";
    arrayOfString['Ԃ'] = "JAIL";
    arrayOfString['ԃ'] = "JAKE";
    arrayOfString['Ԅ'] = "JANE";
    arrayOfString['ԅ'] = "JAVA";
    arrayOfString['Ԇ'] = "JEAN";
    arrayOfString['ԇ'] = "JEFF";
    arrayOfString['Ԉ'] = "JERK";
    arrayOfString['ԉ'] = "JESS";
    arrayOfString['Ԋ'] = "JEST";
    arrayOfString['ԋ'] = "JIBE";
    arrayOfString['Ԍ'] = "JILL";
    arrayOfString['ԍ'] = "JILT";
    arrayOfString['Ԏ'] = "JIVE";
    arrayOfString['ԏ'] = "JOAN";
    arrayOfString['Ԑ'] = "JOBS";
    arrayOfString['ԑ'] = "JOCK";
    arrayOfString['Ԓ'] = "JOEL";
    arrayOfString['ԓ'] = "JOEY";
    arrayOfString['Ԕ'] = "JOHN";
    arrayOfString['ԕ'] = "JOIN";
    arrayOfString['Ԗ'] = "JOKE";
    arrayOfString['ԗ'] = "JOLT";
    arrayOfString['Ԙ'] = "JOVE";
    arrayOfString['ԙ'] = "JUDD";
    arrayOfString['Ԛ'] = "JUDE";
    arrayOfString['ԛ'] = "JUDO";
    arrayOfString['Ԝ'] = "JUDY";
    arrayOfString['ԝ'] = "JUJU";
    arrayOfString['Ԟ'] = "JUKE";
    arrayOfString['ԟ'] = "JULY";
    arrayOfString['Ԡ'] = "JUNE";
    arrayOfString['ԡ'] = "JUNK";
    arrayOfString['Ԣ'] = "JUNO";
    arrayOfString['ԣ'] = "JURY";
    arrayOfString['Ԥ'] = "JUST";
    arrayOfString['ԥ'] = "JUTE";
    arrayOfString['Ԧ'] = "KAHN";
    arrayOfString['ԧ'] = "KALE";
    arrayOfString['Ԩ'] = "KANE";
    arrayOfString['ԩ'] = "KANT";
    arrayOfString['Ԫ'] = "KARL";
    arrayOfString['ԫ'] = "KATE";
    arrayOfString['Ԭ'] = "KEEL";
    arrayOfString['ԭ'] = "KEEN";
    arrayOfString['Ԯ'] = "KENO";
    arrayOfString['ԯ'] = "KENT";
    arrayOfString['԰'] = "KERN";
    arrayOfString['Ա'] = "KERR";
    arrayOfString['Բ'] = "KEYS";
    arrayOfString['Գ'] = "KICK";
    arrayOfString['Դ'] = "KILL";
    arrayOfString['Ե'] = "KIND";
    arrayOfString['Զ'] = "KING";
    arrayOfString['Է'] = "KIRK";
    arrayOfString['Ը'] = "KISS";
    arrayOfString['Թ'] = "KITE";
    arrayOfString['Ժ'] = "KLAN";
    arrayOfString['Ի'] = "KNEE";
    arrayOfString['Լ'] = "KNEW";
    arrayOfString['Խ'] = "KNIT";
    arrayOfString['Ծ'] = "KNOB";
    arrayOfString['Կ'] = "KNOT";
    arrayOfString['Հ'] = "KNOW";
    arrayOfString['Ձ'] = "KOCH";
    arrayOfString['Ղ'] = "KONG";
    arrayOfString['Ճ'] = "KUDO";
    arrayOfString['Մ'] = "KURD";
    arrayOfString['Յ'] = "KURT";
    arrayOfString['Ն'] = "KYLE";
    arrayOfString['Շ'] = "LACE";
    arrayOfString['Ո'] = "LACK";
    arrayOfString['Չ'] = "LACY";
    arrayOfString['Պ'] = "LADY";
    arrayOfString['Ջ'] = "LAID";
    arrayOfString['Ռ'] = "LAIN";
    arrayOfString['Ս'] = "LAIR";
    arrayOfString['Վ'] = "LAKE";
    arrayOfString['Տ'] = "LAMB";
    arrayOfString['Ր'] = "LAME";
    arrayOfString['Ց'] = "LAND";
    arrayOfString['Ւ'] = "LANE";
    arrayOfString['Փ'] = "LANG";
    arrayOfString['Ք'] = "LARD";
    arrayOfString['Օ'] = "LARK";
    arrayOfString['Ֆ'] = "LASS";
    arrayOfString['՗'] = "LAST";
    arrayOfString['՘'] = "LATE";
    arrayOfString['ՙ'] = "LAUD";
    arrayOfString['՚'] = "LAVA";
    arrayOfString['՛'] = "LAWN";
    arrayOfString['՜'] = "LAWS";
    arrayOfString['՝'] = "LAYS";
    arrayOfString['՞'] = "LEAD";
    arrayOfString['՟'] = "LEAF";
    arrayOfString['ՠ'] = "LEAK";
    arrayOfString['ա'] = "LEAN";
    arrayOfString['բ'] = "LEAR";
    arrayOfString['գ'] = "LEEK";
    arrayOfString['դ'] = "LEER";
    arrayOfString['ե'] = "LEFT";
    arrayOfString['զ'] = "LEND";
    arrayOfString['է'] = "LENS";
    arrayOfString['ը'] = "LENT";
    arrayOfString['թ'] = "LEON";
    arrayOfString['ժ'] = "LESK";
    arrayOfString['ի'] = "LESS";
    arrayOfString['լ'] = "LEST";
    arrayOfString['խ'] = "LETS";
    arrayOfString['ծ'] = "LIAR";
    arrayOfString['կ'] = "LICE";
    arrayOfString['հ'] = "LICK";
    arrayOfString['ձ'] = "LIED";
    arrayOfString['ղ'] = "LIEN";
    arrayOfString['ճ'] = "LIES";
    arrayOfString['մ'] = "LIEU";
    arrayOfString['յ'] = "LIFE";
    arrayOfString['ն'] = "LIFT";
    arrayOfString['շ'] = "LIKE";
    arrayOfString['ո'] = "LILA";
    arrayOfString['չ'] = "LILT";
    arrayOfString['պ'] = "LILY";
    arrayOfString['ջ'] = "LIMA";
    arrayOfString['ռ'] = "LIMB";
    arrayOfString['ս'] = "LIME";
    arrayOfString['վ'] = "LIND";
    arrayOfString['տ'] = "LINE";
    arrayOfString['ր'] = "LINK";
    arrayOfString['ց'] = "LINT";
    arrayOfString['ւ'] = "LION";
    arrayOfString['փ'] = "LISA";
    arrayOfString['ք'] = "LIST";
    arrayOfString['օ'] = "LIVE";
    arrayOfString['ֆ'] = "LOAD";
    arrayOfString['և'] = "LOAF";
    arrayOfString['ֈ'] = "LOAM";
    arrayOfString['։'] = "LOAN";
    arrayOfString['֊'] = "LOCK";
    arrayOfString['֋'] = "LOFT";
    arrayOfString['֌'] = "LOGE";
    arrayOfString['֍'] = "LOIS";
    arrayOfString['֎'] = "LOLA";
    arrayOfString['֏'] = "LONE";
    arrayOfString['֐'] = "LONG";
    arrayOfString['֑'] = "LOOK";
    arrayOfString['֒'] = "LOON";
    arrayOfString['֓'] = "LOOT";
    arrayOfString['֔'] = "LORD";
    arrayOfString['֕'] = "LORE";
    arrayOfString['֖'] = "LOSE";
    arrayOfString['֗'] = "LOSS";
    arrayOfString['֘'] = "LOST";
    arrayOfString['֙'] = "LOUD";
    arrayOfString['֚'] = "LOVE";
    arrayOfString['֛'] = "LOWE";
    arrayOfString['֜'] = "LUCK";
    arrayOfString['֝'] = "LUCY";
    arrayOfString['֞'] = "LUGE";
    arrayOfString['֟'] = "LUKE";
    arrayOfString['֠'] = "LULU";
    arrayOfString['֡'] = "LUND";
    arrayOfString['֢'] = "LUNG";
    arrayOfString['֣'] = "LURA";
    arrayOfString['֤'] = "LURE";
    arrayOfString['֥'] = "LURK";
    arrayOfString['֦'] = "LUSH";
    arrayOfString['֧'] = "LUST";
    arrayOfString['֨'] = "LYLE";
    arrayOfString['֩'] = "LYNN";
    arrayOfString['֪'] = "LYON";
    arrayOfString['֫'] = "LYRA";
    arrayOfString['֬'] = "MACE";
    arrayOfString['֭'] = "MADE";
    arrayOfString['֮'] = "MAGI";
    arrayOfString['֯'] = "MAID";
    arrayOfString['ְ'] = "MAIL";
    arrayOfString['ֱ'] = "MAIN";
    arrayOfString['ֲ'] = "MAKE";
    arrayOfString['ֳ'] = "MALE";
    arrayOfString['ִ'] = "MALI";
    arrayOfString['ֵ'] = "MALL";
    arrayOfString['ֶ'] = "MALT";
    arrayOfString['ַ'] = "MANA";
    arrayOfString['ָ'] = "MANN";
    arrayOfString['ֹ'] = "MANY";
    arrayOfString['ֺ'] = "MARC";
    arrayOfString['ֻ'] = "MARE";
    arrayOfString['ּ'] = "MARK";
    arrayOfString['ֽ'] = "MARS";
    arrayOfString['־'] = "MART";
    arrayOfString['ֿ'] = "MARY";
    arrayOfString['׀'] = "MASH";
    arrayOfString['ׁ'] = "MASK";
    arrayOfString['ׂ'] = "MASS";
    arrayOfString['׃'] = "MAST";
    arrayOfString['ׄ'] = "MATE";
    arrayOfString['ׅ'] = "MATH";
    arrayOfString['׆'] = "MAUL";
    arrayOfString['ׇ'] = "MAYO";
    arrayOfString['׈'] = "MEAD";
    arrayOfString['׉'] = "MEAL";
    arrayOfString['׊'] = "MEAN";
    arrayOfString['׋'] = "MEAT";
    arrayOfString['׌'] = "MEEK";
    arrayOfString['׍'] = "MEET";
    arrayOfString['׎'] = "MELD";
    arrayOfString['׏'] = "MELT";
    arrayOfString['א'] = "MEMO";
    arrayOfString['ב'] = "MEND";
    arrayOfString['ג'] = "MENU";
    arrayOfString['ד'] = "MERT";
    arrayOfString['ה'] = "MESH";
    arrayOfString['ו'] = "MESS";
    arrayOfString['ז'] = "MICE";
    arrayOfString['ח'] = "MIKE";
    arrayOfString['ט'] = "MILD";
    arrayOfString['י'] = "MILE";
    arrayOfString['ך'] = "MILK";
    arrayOfString['כ'] = "MILL";
    arrayOfString['ל'] = "MILT";
    arrayOfString['ם'] = "MIMI";
    arrayOfString['מ'] = "MIND";
    arrayOfString['ן'] = "MINE";
    arrayOfString['נ'] = "MINI";
    arrayOfString['ס'] = "MINK";
    arrayOfString['ע'] = "MINT";
    arrayOfString['ף'] = "MIRE";
    arrayOfString['פ'] = "MISS";
    arrayOfString['ץ'] = "MIST";
    arrayOfString['צ'] = "MITE";
    arrayOfString['ק'] = "MITT";
    arrayOfString['ר'] = "MOAN";
    arrayOfString['ש'] = "MOAT";
    arrayOfString['ת'] = "MOCK";
    arrayOfString['׫'] = "MODE";
    arrayOfString['׬'] = "MOLD";
    arrayOfString['׭'] = "MOLE";
    arrayOfString['׮'] = "MOLL";
    arrayOfString['ׯ'] = "MOLT";
    arrayOfString['װ'] = "MONA";
    arrayOfString['ױ'] = "MONK";
    arrayOfString['ײ'] = "MONT";
    arrayOfString['׳'] = "MOOD";
    arrayOfString['״'] = "MOON";
    arrayOfString['׵'] = "MOOR";
    arrayOfString['׶'] = "MOOT";
    arrayOfString['׷'] = "MORE";
    arrayOfString['׸'] = "MORN";
    arrayOfString['׹'] = "MORT";
    arrayOfString['׺'] = "MOSS";
    arrayOfString['׻'] = "MOST";
    arrayOfString['׼'] = "MOTH";
    arrayOfString['׽'] = "MOVE";
    arrayOfString['׾'] = "MUCH";
    arrayOfString['׿'] = "MUCK";
    arrayOfString['؀'] = "MUDD";
    arrayOfString['؁'] = "MUFF";
    arrayOfString['؂'] = "MULE";
    arrayOfString['؃'] = "MULL";
    arrayOfString['؄'] = "MURK";
    arrayOfString['؅'] = "MUSH";
    arrayOfString['؆'] = "MUST";
    arrayOfString['؇'] = "MUTE";
    arrayOfString['؈'] = "MUTT";
    arrayOfString['؉'] = "MYRA";
    arrayOfString['؊'] = "MYTH";
    arrayOfString['؋'] = "NAGY";
    arrayOfString['،'] = "NAIL";
    arrayOfString['؍'] = "NAIR";
    arrayOfString['؎'] = "NAME";
    arrayOfString['؏'] = "NARY";
    arrayOfString['ؐ'] = "NASH";
    arrayOfString['ؑ'] = "NAVE";
    arrayOfString['ؒ'] = "NAVY";
    arrayOfString['ؓ'] = "NEAL";
    arrayOfString['ؔ'] = "NEAR";
    arrayOfString['ؕ'] = "NEAT";
    arrayOfString['ؖ'] = "NECK";
    arrayOfString['ؗ'] = "NEED";
    arrayOfString['ؘ'] = "NEIL";
    arrayOfString['ؙ'] = "NELL";
    arrayOfString['ؚ'] = "NEON";
    arrayOfString['؛'] = "NERO";
    arrayOfString['؜'] = "NESS";
    arrayOfString['؝'] = "NEST";
    arrayOfString['؞'] = "NEWS";
    arrayOfString['؟'] = "NEWT";
    arrayOfString['ؠ'] = "NIBS";
    arrayOfString['ء'] = "NICE";
    arrayOfString['آ'] = "NICK";
    arrayOfString['أ'] = "NILE";
    arrayOfString['ؤ'] = "NINA";
    arrayOfString['إ'] = "NINE";
    arrayOfString['ئ'] = "NOAH";
    arrayOfString['ا'] = "NODE";
    arrayOfString['ب'] = "NOEL";
    arrayOfString['ة'] = "NOLL";
    arrayOfString['ت'] = "NONE";
    arrayOfString['ث'] = "NOOK";
    arrayOfString['ج'] = "NOON";
    arrayOfString['ح'] = "NORM";
    arrayOfString['خ'] = "NOSE";
    arrayOfString['د'] = "NOTE";
    arrayOfString['ذ'] = "NOUN";
    arrayOfString['ر'] = "NOVA";
    arrayOfString['ز'] = "NUDE";
    arrayOfString['س'] = "NULL";
    arrayOfString['ش'] = "NUMB";
    arrayOfString['ص'] = "OATH";
    arrayOfString['ض'] = "OBEY";
    arrayOfString['ط'] = "OBOE";
    arrayOfString['ظ'] = "ODIN";
    arrayOfString['ع'] = "OHIO";
    arrayOfString['غ'] = "OILY";
    arrayOfString['ػ'] = "OINT";
    arrayOfString['ؼ'] = "OKAY";
    arrayOfString['ؽ'] = "OLAF";
    arrayOfString['ؾ'] = "OLDY";
    arrayOfString['ؿ'] = "OLGA";
    arrayOfString['ـ'] = "OLIN";
    arrayOfString['ف'] = "OMAN";
    arrayOfString['ق'] = "OMEN";
    arrayOfString['ك'] = "OMIT";
    arrayOfString['ل'] = "ONCE";
    arrayOfString['م'] = "ONES";
    arrayOfString['ن'] = "ONLY";
    arrayOfString['ه'] = "ONTO";
    arrayOfString['و'] = "ONUS";
    arrayOfString['ى'] = "ORAL";
    arrayOfString['ي'] = "ORGY";
    arrayOfString['ً'] = "OSLO";
    arrayOfString['ٌ'] = "OTIS";
    arrayOfString['ٍ'] = "OTTO";
    arrayOfString['َ'] = "OUCH";
    arrayOfString['ُ'] = "OUST";
    arrayOfString['ِ'] = "OUTS";
    arrayOfString['ّ'] = "OVAL";
    arrayOfString['ْ'] = "OVEN";
    arrayOfString['ٓ'] = "OVER";
    arrayOfString['ٔ'] = "OWLY";
    arrayOfString['ٕ'] = "OWNS";
    arrayOfString['ٖ'] = "QUAD";
    arrayOfString['ٗ'] = "QUIT";
    arrayOfString['٘'] = "QUOD";
    arrayOfString['ٙ'] = "RACE";
    arrayOfString['ٚ'] = "RACK";
    arrayOfString['ٛ'] = "RACY";
    arrayOfString['ٜ'] = "RAFT";
    arrayOfString['ٝ'] = "RAGE";
    arrayOfString['ٞ'] = "RAID";
    arrayOfString['ٟ'] = "RAIL";
    arrayOfString['٠'] = "RAIN";
    arrayOfString['١'] = "RAKE";
    arrayOfString['٢'] = "RANK";
    arrayOfString['٣'] = "RANT";
    arrayOfString['٤'] = "RARE";
    arrayOfString['٥'] = "RASH";
    arrayOfString['٦'] = "RATE";
    arrayOfString['٧'] = "RAVE";
    arrayOfString['٨'] = "RAYS";
    arrayOfString['٩'] = "READ";
    arrayOfString['٪'] = "REAL";
    arrayOfString['٫'] = "REAM";
    arrayOfString['٬'] = "REAR";
    arrayOfString['٭'] = "RECK";
    arrayOfString['ٮ'] = "REED";
    arrayOfString['ٯ'] = "REEF";
    arrayOfString['ٰ'] = "REEK";
    arrayOfString['ٱ'] = "REEL";
    arrayOfString['ٲ'] = "REID";
    arrayOfString['ٳ'] = "REIN";
    arrayOfString['ٴ'] = "RENA";
    arrayOfString['ٵ'] = "REND";
    arrayOfString['ٶ'] = "RENT";
    arrayOfString['ٷ'] = "REST";
    arrayOfString['ٸ'] = "RICE";
    arrayOfString['ٹ'] = "RICH";
    arrayOfString['ٺ'] = "RICK";
    arrayOfString['ٻ'] = "RIDE";
    arrayOfString['ټ'] = "RIFT";
    arrayOfString['ٽ'] = "RILL";
    arrayOfString['پ'] = "RIME";
    arrayOfString['ٿ'] = "RING";
    arrayOfString['ڀ'] = "RINK";
    arrayOfString['ځ'] = "RISE";
    arrayOfString['ڂ'] = "RISK";
    arrayOfString['ڃ'] = "RITE";
    arrayOfString['ڄ'] = "ROAD";
    arrayOfString['څ'] = "ROAM";
    arrayOfString['چ'] = "ROAR";
    arrayOfString['ڇ'] = "ROBE";
    arrayOfString['ڈ'] = "ROCK";
    arrayOfString['ډ'] = "RODE";
    arrayOfString['ڊ'] = "ROIL";
    arrayOfString['ڋ'] = "ROLL";
    arrayOfString['ڌ'] = "ROME";
    arrayOfString['ڍ'] = "ROOD";
    arrayOfString['ڎ'] = "ROOF";
    arrayOfString['ڏ'] = "ROOK";
    arrayOfString['ڐ'] = "ROOM";
    arrayOfString['ڑ'] = "ROOT";
    arrayOfString['ڒ'] = "ROSA";
    arrayOfString['ړ'] = "ROSE";
    arrayOfString['ڔ'] = "ROSS";
    arrayOfString['ڕ'] = "ROSY";
    arrayOfString['ږ'] = "ROTH";
    arrayOfString['ڗ'] = "ROUT";
    arrayOfString['ژ'] = "ROVE";
    arrayOfString['ڙ'] = "ROWE";
    arrayOfString['ښ'] = "ROWS";
    arrayOfString['ڛ'] = "RUBE";
    arrayOfString['ڜ'] = "RUBY";
    arrayOfString['ڝ'] = "RUDE";
    arrayOfString['ڞ'] = "RUDY";
    arrayOfString['ڟ'] = "RUIN";
    arrayOfString['ڠ'] = "RULE";
    arrayOfString['ڡ'] = "RUNG";
    arrayOfString['ڢ'] = "RUNS";
    arrayOfString['ڣ'] = "RUNT";
    arrayOfString['ڤ'] = "RUSE";
    arrayOfString['ڥ'] = "RUSH";
    arrayOfString['ڦ'] = "RUSK";
    arrayOfString['ڧ'] = "RUSS";
    arrayOfString['ڨ'] = "RUST";
    arrayOfString['ک'] = "RUTH";
    arrayOfString['ڪ'] = "SACK";
    arrayOfString['ګ'] = "SAFE";
    arrayOfString['ڬ'] = "SAGE";
    arrayOfString['ڭ'] = "SAID";
    arrayOfString['ڮ'] = "SAIL";
    arrayOfString['گ'] = "SALE";
    arrayOfString['ڰ'] = "SALK";
    arrayOfString['ڱ'] = "SALT";
    arrayOfString['ڲ'] = "SAME";
    arrayOfString['ڳ'] = "SAND";
    arrayOfString['ڴ'] = "SANE";
    arrayOfString['ڵ'] = "SANG";
    arrayOfString['ڶ'] = "SANK";
    arrayOfString['ڷ'] = "SARA";
    arrayOfString['ڸ'] = "SAUL";
    arrayOfString['ڹ'] = "SAVE";
    arrayOfString['ں'] = "SAYS";
    arrayOfString['ڻ'] = "SCAN";
    arrayOfString['ڼ'] = "SCAR";
    arrayOfString['ڽ'] = "SCAT";
    arrayOfString['ھ'] = "SCOT";
    arrayOfString['ڿ'] = "SEAL";
    arrayOfString['ۀ'] = "SEAM";
    arrayOfString['ہ'] = "SEAR";
    arrayOfString['ۂ'] = "SEAT";
    arrayOfString['ۃ'] = "SEED";
    arrayOfString['ۄ'] = "SEEK";
    arrayOfString['ۅ'] = "SEEM";
    arrayOfString['ۆ'] = "SEEN";
    arrayOfString['ۇ'] = "SEES";
    arrayOfString['ۈ'] = "SELF";
    arrayOfString['ۉ'] = "SELL";
    arrayOfString['ۊ'] = "SEND";
    arrayOfString['ۋ'] = "SENT";
    arrayOfString['ی'] = "SETS";
    arrayOfString['ۍ'] = "SEWN";
    arrayOfString['ێ'] = "SHAG";
    arrayOfString['ۏ'] = "SHAM";
    arrayOfString['ې'] = "SHAW";
    arrayOfString['ۑ'] = "SHAY";
    arrayOfString['ے'] = "SHED";
    arrayOfString['ۓ'] = "SHIM";
    arrayOfString['۔'] = "SHIN";
    arrayOfString['ە'] = "SHOD";
    arrayOfString['ۖ'] = "SHOE";
    arrayOfString['ۗ'] = "SHOT";
    arrayOfString['ۘ'] = "SHOW";
    arrayOfString['ۙ'] = "SHUN";
    arrayOfString['ۚ'] = "SHUT";
    arrayOfString['ۛ'] = "SICK";
    arrayOfString['ۜ'] = "SIDE";
    arrayOfString['۝'] = "SIFT";
    arrayOfString['۞'] = "SIGH";
    arrayOfString['۟'] = "SIGN";
    arrayOfString['۠'] = "SILK";
    arrayOfString['ۡ'] = "SILL";
    arrayOfString['ۢ'] = "SILO";
    arrayOfString['ۣ'] = "SILT";
    arrayOfString['ۤ'] = "SINE";
    arrayOfString['ۥ'] = "SING";
    arrayOfString['ۦ'] = "SINK";
    arrayOfString['ۧ'] = "SIRE";
    arrayOfString['ۨ'] = "SITE";
    arrayOfString['۩'] = "SITS";
    arrayOfString['۪'] = "SITU";
    arrayOfString['۫'] = "SKAT";
    arrayOfString['۬'] = "SKEW";
    arrayOfString['ۭ'] = "SKID";
    arrayOfString['ۮ'] = "SKIM";
    arrayOfString['ۯ'] = "SKIN";
    arrayOfString['۰'] = "SKIT";
    arrayOfString['۱'] = "SLAB";
    arrayOfString['۲'] = "SLAM";
    arrayOfString['۳'] = "SLAT";
    arrayOfString['۴'] = "SLAY";
    arrayOfString['۵'] = "SLED";
    arrayOfString['۶'] = "SLEW";
    arrayOfString['۷'] = "SLID";
    arrayOfString['۸'] = "SLIM";
    arrayOfString['۹'] = "SLIT";
    arrayOfString['ۺ'] = "SLOB";
    arrayOfString['ۻ'] = "SLOG";
    arrayOfString['ۼ'] = "SLOT";
    arrayOfString['۽'] = "SLOW";
    arrayOfString['۾'] = "SLUG";
    arrayOfString['ۿ'] = "SLUM";
    arrayOfString['܀'] = "SLUR";
    arrayOfString['܁'] = "SMOG";
    arrayOfString['܂'] = "SMUG";
    arrayOfString['܃'] = "SNAG";
    arrayOfString['܄'] = "SNOB";
    arrayOfString['܅'] = "SNOW";
    arrayOfString['܆'] = "SNUB";
    arrayOfString['܇'] = "SNUG";
    arrayOfString['܈'] = "SOAK";
    arrayOfString['܉'] = "SOAR";
    arrayOfString['܊'] = "SOCK";
    arrayOfString['܋'] = "SODA";
    arrayOfString['܌'] = "SOFA";
    arrayOfString['܍'] = "SOFT";
    arrayOfString['܎'] = "SOIL";
    arrayOfString['܏'] = "SOLD";
    arrayOfString['ܐ'] = "SOME";
    arrayOfString['ܑ'] = "SONG";
    arrayOfString['ܒ'] = "SOON";
    arrayOfString['ܓ'] = "SOOT";
    arrayOfString['ܔ'] = "SORE";
    arrayOfString['ܕ'] = "SORT";
    arrayOfString['ܖ'] = "SOUL";
    arrayOfString['ܗ'] = "SOUR";
    arrayOfString['ܘ'] = "SOWN";
    arrayOfString['ܙ'] = "STAB";
    arrayOfString['ܚ'] = "STAG";
    arrayOfString['ܛ'] = "STAN";
    arrayOfString['ܜ'] = "STAR";
    arrayOfString['ܝ'] = "STAY";
    arrayOfString['ܞ'] = "STEM";
    arrayOfString['ܟ'] = "STEW";
    arrayOfString['ܠ'] = "STIR";
    arrayOfString['ܡ'] = "STOW";
    arrayOfString['ܢ'] = "STUB";
    arrayOfString['ܣ'] = "STUN";
    arrayOfString['ܤ'] = "SUCH";
    arrayOfString['ܥ'] = "SUDS";
    arrayOfString['ܦ'] = "SUIT";
    arrayOfString['ܧ'] = "SULK";
    arrayOfString['ܨ'] = "SUMS";
    arrayOfString['ܩ'] = "SUNG";
    arrayOfString['ܪ'] = "SUNK";
    arrayOfString['ܫ'] = "SURE";
    arrayOfString['ܬ'] = "SURF";
    arrayOfString['ܭ'] = "SWAB";
    arrayOfString['ܮ'] = "SWAG";
    arrayOfString['ܯ'] = "SWAM";
    arrayOfString['ܰ'] = "SWAN";
    arrayOfString['ܱ'] = "SWAT";
    arrayOfString['ܲ'] = "SWAY";
    arrayOfString['ܳ'] = "SWIM";
    arrayOfString['ܴ'] = "SWUM";
    arrayOfString['ܵ'] = "TACK";
    arrayOfString['ܶ'] = "TACT";
    arrayOfString['ܷ'] = "TAIL";
    arrayOfString['ܸ'] = "TAKE";
    arrayOfString['ܹ'] = "TALE";
    arrayOfString['ܺ'] = "TALK";
    arrayOfString['ܻ'] = "TALL";
    arrayOfString['ܼ'] = "TANK";
    arrayOfString['ܽ'] = "TASK";
    arrayOfString['ܾ'] = "TATE";
    arrayOfString['ܿ'] = "TAUT";
    arrayOfString['݀'] = "TEAL";
    arrayOfString['݁'] = "TEAM";
    arrayOfString['݂'] = "TEAR";
    arrayOfString['݃'] = "TECH";
    arrayOfString['݄'] = "TEEM";
    arrayOfString['݅'] = "TEEN";
    arrayOfString['݆'] = "TEET";
    arrayOfString['݇'] = "TELL";
    arrayOfString['݈'] = "TEND";
    arrayOfString['݉'] = "TENT";
    arrayOfString['݊'] = "TERM";
    arrayOfString['݋'] = "TERN";
    arrayOfString['݌'] = "TESS";
    arrayOfString['ݍ'] = "TEST";
    arrayOfString['ݎ'] = "THAN";
    arrayOfString['ݏ'] = "THAT";
    arrayOfString['ݐ'] = "THEE";
    arrayOfString['ݑ'] = "THEM";
    arrayOfString['ݒ'] = "THEN";
    arrayOfString['ݓ'] = "THEY";
    arrayOfString['ݔ'] = "THIN";
    arrayOfString['ݕ'] = "THIS";
    arrayOfString['ݖ'] = "THUD";
    arrayOfString['ݗ'] = "THUG";
    arrayOfString['ݘ'] = "TICK";
    arrayOfString['ݙ'] = "TIDE";
    arrayOfString['ݚ'] = "TIDY";
    arrayOfString['ݛ'] = "TIED";
    arrayOfString['ݜ'] = "TIER";
    arrayOfString['ݝ'] = "TILE";
    arrayOfString['ݞ'] = "TILL";
    arrayOfString['ݟ'] = "TILT";
    arrayOfString['ݠ'] = "TIME";
    arrayOfString['ݡ'] = "TINA";
    arrayOfString['ݢ'] = "TINE";
    arrayOfString['ݣ'] = "TINT";
    arrayOfString['ݤ'] = "TINY";
    arrayOfString['ݥ'] = "TIRE";
    arrayOfString['ݦ'] = "TOAD";
    arrayOfString['ݧ'] = "TOGO";
    arrayOfString['ݨ'] = "TOIL";
    arrayOfString['ݩ'] = "TOLD";
    arrayOfString['ݪ'] = "TOLL";
    arrayOfString['ݫ'] = "TONE";
    arrayOfString['ݬ'] = "TONG";
    arrayOfString['ݭ'] = "TONY";
    arrayOfString['ݮ'] = "TOOK";
    arrayOfString['ݯ'] = "TOOL";
    arrayOfString['ݰ'] = "TOOT";
    arrayOfString['ݱ'] = "TORE";
    arrayOfString['ݲ'] = "TORN";
    arrayOfString['ݳ'] = "TOTE";
    arrayOfString['ݴ'] = "TOUR";
    arrayOfString['ݵ'] = "TOUT";
    arrayOfString['ݶ'] = "TOWN";
    arrayOfString['ݷ'] = "TRAG";
    arrayOfString['ݸ'] = "TRAM";
    arrayOfString['ݹ'] = "TRAY";
    arrayOfString['ݺ'] = "TREE";
    arrayOfString['ݻ'] = "TREK";
    arrayOfString['ݼ'] = "TRIG";
    arrayOfString['ݽ'] = "TRIM";
    arrayOfString['ݾ'] = "TRIO";
    arrayOfString['ݿ'] = "TROD";
    arrayOfString['ހ'] = "TROT";
    arrayOfString['ށ'] = "TROY";
    arrayOfString['ނ'] = "TRUE";
    arrayOfString['ރ'] = "TUBA";
    arrayOfString['ބ'] = "TUBE";
    arrayOfString['ޅ'] = "TUCK";
    arrayOfString['ކ'] = "TUFT";
    arrayOfString['އ'] = "TUNA";
    arrayOfString['ވ'] = "TUNE";
    arrayOfString['މ'] = "TUNG";
    arrayOfString['ފ'] = "TURF";
    arrayOfString['ދ'] = "TURN";
    arrayOfString['ތ'] = "TUSK";
    arrayOfString['ލ'] = "TWIG";
    arrayOfString['ގ'] = "TWIN";
    arrayOfString['ޏ'] = "TWIT";
    arrayOfString['ސ'] = "ULAN";
    arrayOfString['ޑ'] = "UNIT";
    arrayOfString['ޒ'] = "URGE";
    arrayOfString['ޓ'] = "USED";
    arrayOfString['ޔ'] = "USER";
    arrayOfString['ޕ'] = "USES";
    arrayOfString['ޖ'] = "UTAH";
    arrayOfString['ޗ'] = "VAIL";
    arrayOfString['ޘ'] = "VAIN";
    arrayOfString['ޙ'] = "VALE";
    arrayOfString['ޚ'] = "VARY";
    arrayOfString['ޛ'] = "VASE";
    arrayOfString['ޜ'] = "VAST";
    arrayOfString['ޝ'] = "VEAL";
    arrayOfString['ޞ'] = "VEDA";
    arrayOfString['ޟ'] = "VEIL";
    arrayOfString['ޠ'] = "VEIN";
    arrayOfString['ޡ'] = "VEND";
    arrayOfString['ޢ'] = "VENT";
    arrayOfString['ޣ'] = "VERB";
    arrayOfString['ޤ'] = "VERY";
    arrayOfString['ޥ'] = "VETO";
    arrayOfString['ަ'] = "VICE";
    arrayOfString['ާ'] = "VIEW";
    arrayOfString['ި'] = "VINE";
    arrayOfString['ީ'] = "VISE";
    arrayOfString['ު'] = "VOID";
    arrayOfString['ޫ'] = "VOLT";
    arrayOfString['ެ'] = "VOTE";
    arrayOfString['ޭ'] = "WACK";
    arrayOfString['ޮ'] = "WADE";
    arrayOfString['ޯ'] = "WAGE";
    arrayOfString['ް'] = "WAIL";
    arrayOfString['ޱ'] = "WAIT";
    arrayOfString['޲'] = "WAKE";
    arrayOfString['޳'] = "WALE";
    arrayOfString['޴'] = "WALK";
    arrayOfString['޵'] = "WALL";
    arrayOfString['޶'] = "WALT";
    arrayOfString['޷'] = "WAND";
    arrayOfString['޸'] = "WANE";
    arrayOfString['޹'] = "WANG";
    arrayOfString['޺'] = "WANT";
    arrayOfString['޻'] = "WARD";
    arrayOfString['޼'] = "WARM";
    arrayOfString['޽'] = "WARN";
    arrayOfString['޾'] = "WART";
    arrayOfString['޿'] = "WASH";
    arrayOfString['߀'] = "WAST";
    arrayOfString['߁'] = "WATS";
    arrayOfString['߂'] = "WATT";
    arrayOfString['߃'] = "WAVE";
    arrayOfString['߄'] = "WAVY";
    arrayOfString['߅'] = "WAYS";
    arrayOfString['߆'] = "WEAK";
    arrayOfString['߇'] = "WEAL";
    arrayOfString['߈'] = "WEAN";
    arrayOfString['߉'] = "WEAR";
    arrayOfString['ߊ'] = "WEED";
    arrayOfString['ߋ'] = "WEEK";
    arrayOfString['ߌ'] = "WEIR";
    arrayOfString['ߍ'] = "WELD";
    arrayOfString['ߎ'] = "WELL";
    arrayOfString['ߏ'] = "WELT";
    arrayOfString['ߐ'] = "WENT";
    arrayOfString['ߑ'] = "WERE";
    arrayOfString['ߒ'] = "WERT";
    arrayOfString['ߓ'] = "WEST";
    arrayOfString['ߔ'] = "WHAM";
    arrayOfString['ߕ'] = "WHAT";
    arrayOfString['ߖ'] = "WHEE";
    arrayOfString['ߗ'] = "WHEN";
    arrayOfString['ߘ'] = "WHET";
    arrayOfString['ߙ'] = "WHOA";
    arrayOfString['ߚ'] = "WHOM";
    arrayOfString['ߛ'] = "WICK";
    arrayOfString['ߜ'] = "WIFE";
    arrayOfString['ߝ'] = "WILD";
    arrayOfString['ߞ'] = "WILL";
    arrayOfString['ߟ'] = "WIND";
    arrayOfString['ߠ'] = "WINE";
    arrayOfString['ߡ'] = "WING";
    arrayOfString['ߢ'] = "WINK";
    arrayOfString['ߣ'] = "WINO";
    arrayOfString['ߤ'] = "WIRE";
    arrayOfString['ߥ'] = "WISE";
    arrayOfString['ߦ'] = "WISH";
    arrayOfString['ߧ'] = "WITH";
    arrayOfString['ߨ'] = "WOLF";
    arrayOfString['ߩ'] = "WONT";
    arrayOfString['ߪ'] = "WOOD";
    arrayOfString['߫'] = "WOOL";
    arrayOfString['߬'] = "WORD";
    arrayOfString['߭'] = "WORE";
    arrayOfString['߮'] = "WORK";
    arrayOfString['߯'] = "WORM";
    arrayOfString['߰'] = "WORN";
    arrayOfString['߱'] = "WOVE";
    arrayOfString['߲'] = "WRIT";
    arrayOfString['߳'] = "WYNN";
    arrayOfString['ߴ'] = "YALE";
    arrayOfString['ߵ'] = "YANG";
    arrayOfString['߶'] = "YANK";
    arrayOfString['߷'] = "YARD";
    arrayOfString['߸'] = "YARN";
    arrayOfString['߹'] = "YAWL";
    arrayOfString['ߺ'] = "YAWN";
    arrayOfString['߻'] = "YEAH";
    arrayOfString['߼'] = "YEAR";
    arrayOfString['߽'] = "YELL";
    arrayOfString['߾'] = "YOGA";
    arrayOfString['߿'] = "YOKE";
    Random localRandom = new Random();
    int i = localRandom.nextInt(256);
    int j = localRandom.nextInt(256);
    return arrayOfString[i] + " " + arrayOfString[j];
  }
  
  void HandleReturnValues()
  {
    Log.d("ReplForm", "HandleReturnValues() Called, replResult = " + this.replResult);
    if (this.replResult != null)
    {
      OtherScreenClosed(this.replResultFormName, this.replResult);
      Log.d("ReplForm", "Called OtherScreenClosed");
      this.replResult = null;
    }
  }
  
  public void addLogcatButton(Menu paramMenu)
  {
    if (!ReplApplication.isAcraActive()) {
      return;
    }
    paramMenu.add(0, 0, 4, "Send Error Report").setOnMenuItemClickListener(new MenuItem.OnMenuItemClickListener()
    {
      public boolean onMenuItemClick(MenuItem paramAnonymousMenuItem)
      {
        paramAnonymousMenuItem = ReplForm.this.genReportId();
        ReplApplication.reportError(null, paramAnonymousMenuItem);
        Notifier.oneButtonAlert(Form.activeForm, "Your Report Id is: " + paramAnonymousMenuItem + "<br />Use this ID when reporting this error.", "Error Report Id", "OK");
        return true;
      }
    }).setIcon(17301642);
  }
  
  public void addSettingsButton(Menu paramMenu)
  {
    paramMenu.add(0, 0, 3, "Settings").setOnMenuItemClickListener(new MenuItem.OnMenuItemClickListener()
    {
      public boolean onMenuItemClick(MenuItem paramAnonymousMenuItem)
      {
        PhoneStatus.doSettings();
        return true;
      }
    }).setIcon(17301651);
  }
  
  protected void closeApplicationFromBlocks()
  {
    runOnUiThread(new Runnable()
    {
      public void run()
      {
        Toast.makeText(ReplForm.this, "Closing forms is not currently supported during development.", 1).show();
      }
    });
  }
  
  protected void closeForm(Intent paramIntent)
  {
    RetValManager.popScreen("Not Yet");
  }
  
  public boolean isAssetsLoaded()
  {
    return this.assetsLoaded;
  }
  
  public boolean isDirect()
  {
    return this.isDirect;
  }
  
  public boolean loadComponent(String paramString)
  {
    paramString = new File(paramString);
    if (!paramString.exists()) {}
    while (!paramString.getName().endsWith(".jar")) {
      return false;
    }
    Object localObject1 = activeForm.$context();
    Object localObject2 = paramString.getParentFile().getName();
    activeForm.$context();
    localObject1 = ((Activity)localObject1).getDir((String)localObject2, 0);
    localObject2 = Thread.currentThread().getContextClassLoader();
    paramString = new DexClassLoader(paramString.getAbsolutePath(), ((File)localObject1).getAbsolutePath(), null, (ClassLoader)localObject2);
    Thread.currentThread().setContextClassLoader(paramString);
    return true;
  }
  
  public void loadComponents()
  {
    Object localObject1 = activeForm.$context();
    activeForm.$context();
    File localFile1 = ((Activity)localObject1).getDir("componentDexs", 0);
    Object localObject2 = new File("/sdcard/AppInventor/assets/external_comps/");
    checkComponentDir();
    localObject1 = Thread.currentThread().getContextClassLoader();
    File[] arrayOfFile = ((File)localObject2).listFiles();
    int j = arrayOfFile.length;
    int i = 0;
    while (i < j)
    {
      File localFile2 = arrayOfFile[i];
      localObject2 = localObject1;
      if (localFile2.isDirectory())
      {
        localObject2 = new File(localFile2.getPath() + File.separator + "classes.jar");
        localFile2 = new File(localFile2.getPath() + File.separator + localFile2.getName() + ".jar");
        ((File)localObject2).renameTo(localFile2);
        localObject2 = localObject1;
        if (localFile2.exists())
        {
          localObject2 = localObject1;
          if (!this.loadedExternalDexs.contains(localFile2.getName()))
          {
            this.loadedExternalDexs.add(localFile2.getName());
            localObject2 = new DexClassLoader(localFile2.getAbsolutePath(), localFile1.getAbsolutePath(), null, (ClassLoader)localObject1);
            Thread.currentThread().setContextClassLoader((ClassLoader)localObject2);
          }
        }
      }
      i += 1;
      localObject1 = localObject2;
    }
  }
  
  public void onCreate(Bundle paramBundle)
  {
    super.onCreate(paramBundle);
    Log.d("ReplForm", "onCreate");
    this.loadedExternalDexs = new ArrayList();
    processExtras(getIntent(), false);
  }
  
  public boolean onCreateOptionsMenu(Menu paramMenu)
  {
    super.onCreateOptionsMenu(paramMenu);
    addSettingsButton(paramMenu);
    addLogcatButton(paramMenu);
    return true;
  }
  
  protected void onDestroy()
  {
    super.onDestroy();
    if (this.httpdServer != null)
    {
      this.httpdServer.stop();
      this.httpdServer = null;
    }
    finish();
    System.exit(0);
  }
  
  protected void onNewIntent(Intent paramIntent)
  {
    super.onNewIntent(paramIntent);
    Log.d("ReplForm", "onNewIntent Called");
    processExtras(paramIntent, true);
  }
  
  protected void onResume()
  {
    super.onResume();
  }
  
  protected void onStop()
  {
    super.onStop();
  }
  
  protected void processExtras(Intent paramIntent, boolean paramBoolean)
  {
    paramIntent = paramIntent.getExtras();
    if (paramIntent != null)
    {
      Log.d("ReplForm", "extras: " + paramIntent);
      Iterator localIterator = paramIntent.keySet().iterator();
      while (localIterator.hasNext()) {
        Log.d("ReplForm", "Extra Key: " + (String)localIterator.next());
      }
    }
    if ((paramIntent != null) && (paramIntent.getBoolean("rundirect")))
    {
      Log.d("ReplForm", "processExtras rundirect is true and restart is " + paramBoolean);
      this.isDirect = true;
      this.assetsLoaded = true;
      if (paramBoolean)
      {
        clear();
        if (this.httpdServer == null) {
          break label167;
        }
        this.httpdServer.resetSeq();
      }
    }
    return;
    label167:
    startHTTPD(true);
    paramIntent = this.httpdServer;
    AppInvHTTPD.setHmacKey("emulator");
  }
  
  public void setAssetsLoaded()
  {
    this.assetsLoaded = true;
  }
  
  public void setFormName(String paramString)
  {
    this.formName = paramString;
    Log.d("ReplForm", "formName is now " + paramString);
  }
  
  public void setIsUSBrepl()
  {
    this.IsUSBRepl = true;
  }
  
  protected void setResult(Object paramObject)
  {
    Log.d("ReplForm", "setResult: " + paramObject);
    this.replResult = paramObject;
    this.replResultFormName = this.formName;
  }
  
  public void startHTTPD(boolean paramBoolean)
  {
    try
    {
      if (this.httpdServer == null)
      {
        checkAssetDir();
        this.httpdServer = new AppInvHTTPD(8001, new File("/sdcard/AppInventor/assets/"), paramBoolean, this);
        Log.i("ReplForm", "started AppInvHTTPD");
      }
      return;
    }
    catch (IOException localIOException)
    {
      Log.e("ReplForm", "Setting up NanoHTTPD: " + localIOException.toString());
    }
  }
  
  protected void startNewForm(String paramString, Object paramObject)
  {
    if (paramObject != null) {
      this.startupValue = jsonEncodeForForm(paramObject, "open another screen with start value");
    }
    RetValManager.pushScreen(paramString, paramObject);
  }
}


/* Location:              C:\Users\Mohamed\Downloads\dex2jar-2.0\dex2jar-2.0\classes-dex2jar.jar!\com\google\appinventor\components\runtime\ReplForm.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */